Нагаев Дмитрий
urfu-2016/javascript-task-3 pull request #10
Opened 2016-10-22 09:12 UTC by fng3r

2016-10-22 09:12 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-22 11:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-22 11:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-22 11:56 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-22 11:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-22 12:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-22 12:05 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-22 12:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2016-10-22 13:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-22 13:03 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2016-10-23 17:35 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 16

2016-10-23 17:46 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-23 17:46 UTC, honest-hrundel commented
@Dodo888 обрати внимание решено доп. задание

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +var DAYS_OF_WEEK = ['ПН', 'ВТ', 'СР'];
По названию сложно догадаться, что массив всего из 3 элементов

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    return (time.length === 2 ? time : '0' + time);
Можно записать `(time.length === 2 ? '' : '0') + time`

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    var timezoneOffset = Number(match[4]) - bankTimezone;
Здесь ты используешь объектную обёртку над числом. Вместо неё лучше использовать parseInt

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +function isTimeIn(time, interval) {
Название `isTimeInInterval` будет более понятно читателю)

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    var timezoneOffset = Number(match[4]) - bankTimezone;
По названию метода непонятно, что у даты ещё меняется оффсет. Я бы вынес изменение оффсета в отдельный метод

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    var parsed = {};
`parsed`, конечно, хорошо, но `parsedInterval` лучше

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    parsed.from = parseDate(interval.from, bankTimezone);
Можно сразу создавать объект с нужными полями, например:
`var parsed = {
from: parseDate(interval.from, bankTimezone)
}`

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    var parsed = [];
И тут тоже `parsed` можно заменить

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    var general = joinIntervals(sortedSchedule);
Непонятно, что имеется ввиду под названием переменной

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    var bankTimezone = Number(/\+(\d+)/.exec(workingHours.from)[1]);
Здесь тоже лучше использовать примитивный тип вместо объектной оболочки

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    var timeToRob = [];
Скорее это время занятости, чем время для ограбления

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +function getRobberyTime(freeSchedule, bankSchedule, duration) {
Название метода не согласуется с тем, что он возвращает. Если возвращается массив, то лучше в названии употребить множественное число.

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +        timeToRob.push(interval);
Возможны случаи, когда в массив будут попадать интервалы нулевой длины. Можно сразу эти случаи обрабатывать

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    time = String(time);
Здесь лучше использовать неявное преобразование, чем создавать объектную обертку для строки

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +    var timeToRob = [];
Название самого массива тоже во множественном числе)

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +                } else if (this.robberyTimes.length > 1) {
else тоже лучше обернуть в фигурные скобки. В любой момент ты можешь захотеть дописать что-нибудь в него, так что лучше написать их сразу, чем забыть сделать это потом)

2016-10-23 20:35 UTC, Dodo888 commented on robbery.js
> +                if (isTimeIn(newTime, this.nearestInterval) &&
Для упрощения можно вынести ещё одну маленькую функцию, которая будет проверять вхождения одного интервала в другой

2016-10-23 20:35 UTC, Dodo888 commented
:tomato:

2016-10-24 07:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-24 07:07 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-24 07:07 UTC, honest-hrundel commented
@Dodo888 обрати внимание решено доп. задание

2016-10-24 07:08 UTC, fng3r commented on robbery.js
> +                } else if (this.robberyTimes.length > 1) {
линтер не позволил

2016-10-24 17:37 UTC, Dodo888 commented on robbery.js
> +    time = time.toString();
Входной параметр лучше не менять. Вдруг мы забудем, что уже меняли его и захотим снова использовать его?

2016-10-24 17:37 UTC, Dodo888 commented on robbery.js
> +    var parserSchedule = [];
`parsed`*

2016-10-24 17:37 UTC, Dodo888 commented on robbery.js
> +    var bankTimezone = parseInt(/\+(\d+)/.exec(workingHours.from)[1], 10);
Слишком много действий для одной строки. Кажется, можно разбить её на несколько

2016-10-24 17:37 UTC, Dodo888 commented on robbery.js
> +function getRobberyTimes(freeSchedule, bankSchedule, duration) {
`robberyDuration`

2016-10-24 17:37 UTC, Dodo888 commented on robbery.js
> +    var start = schedule[0];
Тут ты кладешь в start ссылку на тот же объект, поэтому в массиве этот объект также будет изменяться. Для клонирования объекта советую использовать `Object.assign({}, obj)`

2016-10-24 17:37 UTC, Dodo888 commented on robbery.js
> +            start.to = start.to < interval.to ? interval.to : start.to;
чуть ниже для этого же самого ты используешь `Math.max`

2016-10-24 17:38 UTC, Dodo888 commented on robbery.js
> +                } else if (this.robberyTimes.length > 1) {
Ну раз линтер не хочет, то ладно)

2016-10-24 17:38 UTC, Dodo888 commented
:tomato:

2016-10-24 17:52 UTC, fng3r commented on robbery.js
> +    var start = schedule[0];
Этот массив ни для чего более и не используется, кроме как для преобразования его элементов. Да, функция грязная, но в данном контексте это не имеет значения, так как дальше исходный массив нигде использоваться не будет.

2016-10-24 17:53 UTC, fng3r commented on robbery.js
> +    var parserSchedule = [];
Безусловно

2016-10-24 18:05 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-24 18:05 UTC, honest-hrundel commented
@Dodo888 обрати внимание решено доп. задание

2016-10-24 18:41 UTC, Dodo888 commented on robbery.js
> +    var start = schedule[0];
Грязная функция хороша только до тех пор, пока ты помнишь, что она грязная. В данной задаче, конечно, ничего плохого не будет, но в общем случае лучше не забывать о таких особенностях js и применять превентивные меры

2016-10-24 18:58 UTC, Dodo888 commented on robbery.js
> +    var regEx = /([А-Я]{2}) (\d\d):(\d\d)\+(\d+)/g;
Вместо `\d\d` можно также писать `\d{2}`

2016-10-24 18:58 UTC, Dodo888 commented on robbery.js
> +function getGeneralSchedule(schedule, bankTimezone) {
Название метода не совсем точно описывает то, что метод возвращает, особенно учитывая, что в самом методе ты используешь переменную generalSchedule для другого расписания

2016-10-24 18:58 UTC, Dodo888 commented on robbery.js
> +    var bankTimezone = parseInt(bankTimezoneMatch, 10);
👍

2016-10-24 19:00 UTC, Dodo888 commented
:tomato:

2016-10-24 19:16 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-24 19:16 UTC, honest-hrundel commented
@Dodo888 обрати внимание решено доп. задание

2016-10-24 20:08 UTC, Dodo888 commented
🚀

2016-10-25 05:41 UTC, dzlk commented on robbery.js
> +var ROBBERY_DAYS = ['ПН', 'ВТ', 'СР'];
Зачем ты выпилил все JsDoc? Давай-ка их обратно вернем. Правило хорошего тона, документировать публичные методы, тем более, что по параметрам сложно догадаться об их стурктуре

2016-10-25 05:44 UTC, dzlk commented on robbery.js
> +function getBankSchedule(bankHours, bankTimezone) {
Есть прекрасное правило по размещению функций. Оно не обязательное, а как рекомендация.
Все используемые функции размещать ниже и располагать схожие по смыслу рядом. Это позволит код читать не рвано – прыгая, то вверх, то в низ,  а сверху вниз. С этим правилом уходят вопросы, где разместить функцию.

2016-10-25 05:46 UTC, dzlk commented on robbery.js
> +        return parseInterval(dayInterval, bankTimezone);
наличие bankTimezone в этой функции выглядит бессмысленно, так как он есть в часах работы

2016-10-25 05:48 UTC, dzlk commented on robbery.js
> +    var regEx = /([А-Я]{2}) (\d{2}):(\d{2})\+(\d+)/g;
❗️ Создается при каждом вызове функции. Имя ничего не отражающее

2016-10-25 05:48 UTC, dzlk commented on robbery.js
> +function getBankSchedule(bankHours, bankTimezone) {
У тебя кстати, сейчас последовательность функций хаотичная, что сильно усложняет чтение

2016-10-25 06:38 UTC, dzlk requested changes
У тебя проблема с последовательностью функций, с огромным количеством названий одной и той же сущности. Очень сильно запутывает связка трех функций: getFreeIntervals, getFreeSchedule и getRobberyTimes

Все, что помечено ❗️ нужно поправить, остальное по втоему усмотрению

2016-10-25 06:38 UTC, dzlk commented on robbery.js
> +    var timesToRob = getRobberyTimes(generalSchedule, bankSchedule, duration);
4-ре символа сэкономил в названии?

2016-10-25 06:38 UTC, dzlk commented on robbery.js
> +        get nearestInterval() {
❗️ этого не было в API

2016-10-25 06:38 UTC, dzlk commented on robbery.js
> +    return new Date(1970, 5, day, hours, minutes);
Можно было вообще не использовать Date

2016-10-25 06:38 UTC, dzlk commented on robbery.js
> +    var strTime = time.toString();
можно так `time = time.toString()` и не заводить лишнюю переменную со странным названием

2016-10-25 06:38 UTC, dzlk commented on robbery.js
> +    return (strTime.length === 2 ? '' : '0') + strTime;
я бы сделал так

```
return strTime.length === 1 ? '0' + strTime : strTime
```

2016-10-25 06:38 UTC, dzlk commented on robbery.js
> +    Object.keys(schedule).forEach(function (bandit) {
Штож сразу бандит-то

2016-10-25 06:38 UTC, dzlk commented on robbery.js
> +    return parsedSchedule;
❗️ Давай через reduce

2016-10-25 06:38 UTC, dzlk commented on robbery.js
> +    businessSchedule.forEach(function (currentInterval) {
сколько же вариаций schedule у тебя. Тут кстати ошибка еще в слове бизнес

2016-10-25 06:38 UTC, dzlk commented on robbery.js
> +function getFreeSchedule(businessSchedule, bankTimezone) {
почему не просто `schedule ` или `generalSchedule`

2016-10-25 06:38 UTC, dzlk commented on robbery.js
> +    generalSchedule.push(start);
❗️ Очень плохое название, оно сбивает с толку

2016-10-25 06:41 UTC, dzlk commented
🍅

2016-10-25 09:32 UTC, fng3r commented on robbery.js
> +    businessSchedule.forEach(function (currentInterval) {
https://www.spellzone.com/dictionary/business

2016-10-25 09:35 UTC, fng3r commented on robbery.js
> +    var strTime = time.toString();
Студентор посоветовал выделить отдельную переменную для возможного дальнейшего использования входного time

2016-10-25 09:36 UTC, fng3r commented on robbery.js
> +    return (strTime.length === 2 ? '' : '0') + strTime;
Вам надо познакомиться

2016-10-25 09:46 UTC, fng3r commented on robbery.js
> +function getFreeSchedule(businessSchedule, bankTimezone) {
general уже использовано под общее смердженное расписание
schedule - слишком абстрактно

2016-10-25 09:51 UTC, dzlk commented on robbery.js
> +    businessSchedule.forEach(function (currentInterval) {
Окей, попутал

2016-10-25 09:52 UTC, dzlk commented on robbery.js
> +function getFreeSchedule(businessSchedule, bankTimezone) {
Дак ты сюда же general передаешь

2016-10-25 09:52 UTC, dzlk commented on robbery.js
> +    return (strTime.length === 2 ? '' : '0') + strTime;
Кому? Ты про что?

2016-10-25 09:56 UTC, dzlk commented on robbery.js
> +    var strTime = time.toString();
Ну это нормально, мы разные люди, у меня одно мнение, у Вовы другое. У него свои аргументы, у меня свои. Если ты заметил, я не пометил это замечание обязательным и оставил выбор тебе

2016-10-25 13:04 UTC, fng3r commented on robbery.js
> +    var strTime = time.toString();
Да, безусловно, заметил. Собственно, я и не настаивал на каком-то определенном варианте

2016-10-25 13:30 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-25 13:30 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-10-25 13:34 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-25 13:34 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-10-25 16:42 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-25 16:42 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-10-26 03:48 UTC, dzlk approved these changes
Хорошо

2016-10-26 03:48 UTC, dzlk commented on robbery.js
> +        }, []);
👍

2016-10-26 03:48 UTC, dzlk commented on robbery.js
> +    time = time.toString();
Переименовать дело пяти секунд, а заводить лишнюю переменную на будущее кажется оверхедом

2016-10-26 03:48 UTC, closed without merging

2016-10-26 03:50 UTC, dzlk commented on robbery.js
> +            });
Тут тоже надо было редьюс загнать, не заметил :(

2016-10-26 04:42 UTC, fng3r commented on robbery.js
> +            });
Но здесь же не нужно аккумулировать какое-либо значение, а лишь следует просто добавить элементы в массив. reduce не будет избыточным?

2016-10-26 05:41 UTC, dzlk commented on robbery.js
> +            });
Ну как не нужно, ты же все сваливаешь в массив. Можно было мапом конечно сделать примерно так
```
Object.keys(schedule).reduce(function (newSchedule, name) {
  var intervals = schedule[name].map(function (interval) {
    return parseInterval(interval, bankTimezone);
  });
  return schedule.concat(intervals);
}, []);
```
Либо