Петров Евгений
urfu-2016/javascript-task-3 pull request #15
Opened 2016-10-23 01:39 UTC by LeMarck

2016-10-23 01:40 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 19

2016-10-23 01:54 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2016-10-23 14:14 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2016-10-23 15:38 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 19

2016-10-24 01:08 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2016-10-24 01:37 UTC, honest-hrundel commented
:tomato: Пройдено тестов 12 из 16

2016-10-24 03:16 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2016-10-24 12:44 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2016-10-25 00:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 19

2016-10-25 01:18 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2016-10-25 02:44 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-25 02:44 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-26 17:00 UTC, m1ralx reviewed
bump

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +var util = require('util');
Давай перепишем без `util`. В данной задаче его использование неоправданно.

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +var DATE = /^([А-Я]{2})?[ ]?(\d\d):(\d\d)\+(\d+)$/;
регвыр можно сделать более простым и читабельным

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +var WEEK = ['ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ', 'ВС'];
Насколько я знаю, можно обойтись без использования лишних дней (ЧТ-ВС)

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            var token = DATE.exec(time);
Бессмысленное имя переменной. Не имеет ничего общего с контекстом задачи.

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            this.timezone = Number(token[4]);
используй `parseInt` с указанием основания системы счисления

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            var token = DATE.exec(time);
Ещё и в единственном числе, хотя это массив

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            this._ticks = WEEK.indexOf(token[1] || 'ПН') * DAY +
И вот уже тут сейчас нужно куда-то там смотреть, соотносить регвыр и порядок элементов в массиве чтобы понять, что тут вообще происходит.

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            return (ticks < 10 ? '0' : '') + ticks;
А правда, что у тебя `ticks` это ни разу не `CPU ticks` и даже не миллисекунды?

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +Object.defineProperties(DateTime.prototype, {
И вообще я тут подумал, что странно как-то писать по сути свой класс `DateTime`, хотя в этой задаче можно обойтись встроенным объектом `Date`

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +        value: function (timezone) {
а если сюда придёт что-то некорректное?

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +        value: function (timezone) {
точнее, не то, что ты ожидаешь

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            return util.format('%s %s:%s+%s', day, hour, minutes, this.timezone);
Вот это уж точно можно легко сделать без использования `util`

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            var hour = this._toTime(Math.floor((ticks % DAY) / HOUR));
`Math.floor(...` лучше вынести в отдельную переменную с хорошим названием, чтобы было понятно

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +var DateTime = function (time) {
лучше использовать функции-конструкторы

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +         * Ограбление
Может быть тогда назвать саму функцию хорошо, а не писать такие комментарии?

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +                var times = this._isBadInterval(this._start.ticks);
кстати, откуда такая любовь к названиям, начинающимся с `_`?

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            return bisyTime;
siriosli?

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            var bisyTime = [];
ну и массив же -- значит множественное число

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +         * Интервалы занятости грабителей
Опять же, почему нельзя назвать нормально функцию и не писать такие комменты?

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            Object.keys(schedule)
Это всё можно заменить на `reduce` и на `map` тоже наверное. А для нормальной читаемости вынести то, что внутри циклов в отдельный метод

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            return this._badInterval
так это ИНТЕРВАЛ (один) или множество интервалов (несколько)?

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +                    return (interval[0] <= start && start < interval[1]) ||
Напиши функцию, название которой будет отражать, что именно проверяется в этом большом условии.

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +                });
ещё раз, функция `_isBadInterval` возвращает массив чего-то, или я неправильно понял?

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            this._start.ticks += 30;
А, так ticks это на самом деле minutes..

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
> +            return this._run();
Лучше найти сразу все подходящие интервалы и не запускать каждый раз поиск на tryLater

2016-10-26 17:00 UTC, mironov-alexey commented on robbery.js
>          exists: function () {
вот эта и ещё две функции ниже какие-то странные. Может всё-таки отказаться от использования "недоклассов" и написать в функциональном стиле без этого бойлерплэйта?

2016-10-26 17:00 UTC, mironov-alexey commented
:tomato:

2016-10-26 17:35 UTC, LeMarck commented on robbery.js
> +var WEEK = ['ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ', 'ВС'];
@mironov-alexey, да можно, но это не вредит решению, а наоборот расширяет его.

2016-10-26 17:36 UTC, LeMarck commented on robbery.js
> +var DATE = /^([А-Я]{2})?[ ]?(\d\d):(\d\d)\+(\d+)$/;
@mironov-alexey, куда ещё более читабельнее?

2016-10-26 17:38 UTC, LeMarck commented on robbery.js
> +Object.defineProperties(DateTime.prototype, {
@mironov-alexey, `Data` не является оптимальным. И чем он мешает? `DateTime` имеет всё, что мне нужно для решения задачи. И не надо плодить какую-то не понятную магию с `new Date()`

2016-10-26 17:39 UTC, LeMarck commented on robbery.js
> +            this.timezone = Number(token[4]);
@mironov-alexey, почему?

2016-10-26 17:40 UTC, LeMarck commented on robbery.js
> +            return (ticks < 10 ? '0' : '') + ticks;
@mironov-alexey, хорошо, переименую))

2016-10-26 17:41 UTC, LeMarck commented on robbery.js
> +        value: function (timezone) {
@mironov-alexey, в условиях задачи сказано, что гарантируется валидность входных данных относительно времени.

2016-10-26 17:43 UTC, LeMarck commented on robbery.js
> +            return util.format('%s %s:%s+%s', day, hour, minutes, this.timezone);
@mironov-alexey, так красивее)) Но хорошо уберу

2016-10-26 17:45 UTC, LeMarck commented on robbery.js
> +         * Интервалы занятости грабителей
@mironov-alexey, хорошо, уберу весь JSDoc, если с ним проблема.

2016-10-26 17:46 UTC, LeMarck commented on robbery.js
> +            return bisyTime;
@mironov-alexey, а можно более расширенное замечание?

2016-10-26 17:48 UTC, LeMarck commented on robbery.js
> +         * Ограбление
@mironov-alexey, проблемы в JSDoc? Он вроде укладывается в кодстайл. Да и название функции подходит.

2016-10-26 17:51 UTC, LeMarck commented on robbery.js
> +                var times = this._isBadInterval(this._start.ticks);
@mironov-alexey, ```_``` указывает на приватность
https://habrahabr.ru/post/251477/

2016-10-26 17:52 UTC, LeMarck commented on robbery.js
> +            return this._run();
@mironov-alexey, почему? Если ```tryLater()``` ни разу не воспользуются, то это бут лишние вычисления.

2016-10-26 17:54 UTC, LeMarck commented on robbery.js
>          exists: function () {
@mironov-alexey, почему?

2016-10-26 17:58 UTC, mironov-alexey commented on robbery.js
> +var WEEK = ['ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ', 'ВС'];
YAGNI

2016-10-26 17:59 UTC, m1ralx commented on robbery.js
> +var DATE = /^([А-Я]{2})?[ ]?(\d\d):(\d\d)\+(\d+)$/;
Например, `\d\d` -> `\d{2}`
`[ ]` -> `\s`

2016-10-26 18:00 UTC, mironov-alexey commented on robbery.js
> +Object.defineProperties(DateTime.prototype, {
Можно плодить понятную магию. По крайней мере другие с этим справляются и обходятся без кучи бойлерплейт кода.

2016-10-26 18:06 UTC, LeMarck commented on robbery.js
> +            var token = DATE.exec(time);
@mironov-alexey, забыл в конце "s" добавить. Сейчас исправлю. А тебе вот ссылочка - https://ru.wikipedia.org/wiki/Токен_(лексический_анализ)

2016-10-26 18:09 UTC, LeMarck commented on robbery.js
> +            var hour = this._toTime(Math.floor((ticks % DAY) / HOUR));
@mironov-alexey, a ```Math.floor(exp)``` чем не угодил?

2016-10-26 18:17 UTC, LeMarck commented on robbery.js
> +                    return (interval[0] <= start && start < interval[1]) ||
@mironov-alexey, я бы предложил подняться на перу строк выше, там есть название метода, которое должно как-то намекнуть на то, что тут происходит))

2016-10-26 18:18 UTC, mironov-alexey commented on robbery.js
> +            var token = DATE.exec(time);
Название переменной всё равно слишком обобщённое. Какое отношение лексический анализ имеет к этой задаче?

2016-10-26 18:19 UTC, mironov-alexey commented on robbery.js
> +            this.timezone = Number(token[4]);
Потому что `parseInt` вернёт либо NaN либо int. `Number` может вернуть float

2016-10-26 18:20 UTC, mironov-alexey commented on robbery.js
> +            var hour = this._toTime(Math.floor((ticks % DAY) / HOUR));
тем, что слишком много действий в одной строке

2016-10-26 18:21 UTC, mironov-alexey commented on robbery.js
> +         * Интервалы занятости грабителей
весь JSDoc убирать не надо. Надо называть функции и переменные так, чтобы по их названию было понятно, что в них происходит.

2016-10-26 18:22 UTC, mironov-alexey commented on robbery.js
> +            return bisyTime;
[busy](https://www.youtube.com/watch?v=m_mDTLphIVY)

2016-10-26 18:29 UTC, LeMarck commented on robbery.js
> +var WEEK = ['ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ', 'ВС'];
@mironov-alexey, это конечно модное слово, но вот в задании есть такая строчечка
```
Все время задачи ограничено неделей c ПН 00:00 до ВС 23:59 в часовом поясе банка
```
И если банк надо ограбить с ПН 00:00 до СР 23:59, это никак не мешает кому-то из участников быть занятым, например с ПТ по ВТ.

2016-10-26 18:31 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-26 18:31 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-26 18:36 UTC, m1ralx reviewed
Имена методов и переменных плохо отражают происходящее. Некоторые методы ничего не делают кроме того, как возвращают результат единственного вызванного метода. Сложные условия проверки.

2016-10-26 18:36 UTC, mironov-alexey commented on robbery.js
> +                    return (interval[0] <= start && start < interval[1]) ||
Проблема в том, что оно очень плохо намекает на то, что здесь происходит. Какой интервал считается "плохим"?  Почему функция возвращает не Boolean, а массив, состоящий из interval[1], где interval удовлетворяет какому-то странному и нечитаемому условию?

2016-10-26 18:36 UTC, mironov-alexey commented on robbery.js
> +         * Ограбление
Название функции не подходит.

2016-10-26 18:36 UTC, mironov-alexey commented on robbery.js
>          exists: function () {
Потому что код станет гораздо более компактным, читабельным и не будет таких странных мест
```javascript
exists: function() {
    return robbery.exists();
}
```
на которых возникают только вопросы: "А зачем? Почему две функции и вторая возвращает напрямую результат первой? Почему нельзя обойтись одной функцией?"

2016-10-26 18:37 UTC, mironov-alexey commented
🍅

2016-10-26 19:40 UTC, mironov-alexey commented on robbery.js
> +    tryLater: {
Когда нет знания о том, сколько раз будет вызван tryLater, кажется лучше будет один раз всё предпосчитать, зато потом быстро отвечать на запросы. Если бы ты делал веб-сервис который умеет на такие вопросы отвечать, ты бы заставлял пользователя ждать каждый раз или только один?

2016-10-27 01:13 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-27 01:46 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-27 01:46 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-27 13:23 UTC, m1ralx reviewed
bump

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +            time = robberyMoments.shift() || oldTime;
шифтить вроде как не надо

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +            return template.replace('%DD', day)
```javascript
return template.replace('%DD', day)
               .replace('%HH', (hour < 10 ? '0' : '') + hour)
               .replace('%MM', (minutes < 10 ? '0' : '') + minutes);
```

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +    var time = robberyMoments.shift();
тут тоже вроде не надо сайд-эффекты плодить

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +    var robbery = new AppropriateMoment(schedule, workingHours);
так это "ограбление" или "подходящий момент"? Какое-то несоответствие в названии переменной и функции-конструктора.

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +    var exists = robberyMoments.length !== 0;
можно это возвращать прямо в функции `exists`.

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +    run: {
назови лучше и понятнее

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +    run: {
функции которые называются в стиле `run` обычно ничего не возвращают

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +                    return (interval[0] <= start && start < interval[1]) ||
Вынести в `isBadInterval`

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +                    schedule[name].forEach(function (interval) {
вынести этот forEach в функцию

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +                .forEach(function (name) {
зачем это переносить? Если не укладываешься в ограничение по длине строки, можно задуматься о декомпозиции

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +                    new DateTime(WEEK[index] + workingHours.to).minutes,
встроенный Date может легко делать то же самое. Не надо изобретать велосипед.

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +            var tokens = DATE.exec(time);
`parsedTime`

2016-10-27 13:23 UTC, mironov-alexey commented on robbery.js
> +var DATE = /^([А-Я]{2})?[ ]?(\d\d):(\d\d)\+(\d+)$/;
`DATE_FORMAT`

2016-10-27 13:23 UTC, mironov-alexey commented
🍅

2016-10-27 16:54 UTC, LeMarck commented on robbery.js
> +    var exists = robberyMoments.length !== 0;
@mironov-alexey, было бы здорово придерживаться одной тактики)) Тебе не понравилось ранее то, что tryLater при каждом вызове делал пересчёты, а теперь ты хочешь, чтобы при каждом вызове exists я делал проверку. Пожалуйста, будь внимательнее при чтении задания!

2016-10-27 16:58 UTC, LeMarck commented on robbery.js
> +    var time = robberyMoments.shift();
@mironov-alexey, я безумно рад, что твой лексикон полон всяких умных иностранных слов, но было бы ещё лучше, если эти слова употреблялись правильно. И читай задание!

2016-10-27 16:59 UTC, LeMarck commented on robbery.js
> +            time = robberyMoments.shift() || oldTime;
@mironov-alexey, вроде как?

2016-10-27 17:01 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-27 17:01 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-27 17:37 UTC, mironov-alexey commented on robbery.js
> +    moment: {
было лучше :trollface:

2016-10-27 17:37 UTC, mironov-alexey commented on robbery.js
> +    var appropriateMoment = new AppropriateMoment(schedule, workingHours);
ща вообще огонь получается. У тебя объект "подходящий момент", название которого как бы намекает, что это момент. А ты у него зовёшь `getMoments`.
У момента
`getMoments`
не кажется странным?

2016-10-27 17:37 UTC, mironov-alexey commented on robbery.js
> +    var exists = robberyMoments.length !== 0;
Подразумевалось, что можно обойтись без удаления элементов из `robberyMoments`. Но да, если их удалять, то конечно эта проверка может находиться только здесь. Про пересчёты тут вообще мимо кассы.

2016-10-27 17:40 UTC, m1ralx reviewed
:trollface:

2016-10-27 17:40 UTC, mironov-alexey commented
🍅

2016-10-27 17:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-27 17:59 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-27 18:12 UTC, mironov-alexey commented
ладн, вроде +/- читабельно стало 🚀

2016-10-28 03:57 UTC, dzlk requested changes
Нужно обязательно обратить внимание на комментарии, помеченные❗️ и как-то на них отреагировать. Остальное на твое усмотрение.

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +Object.defineProperties(Moment.prototype, {
Так, это зачем?

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +var MOMENT_PATTERN = /^([А-Я]{2})?\s?(\d{2}):(\d{2})\+(\d{1,2})$/;
Можно так `/^(?:([А-Я]{2})\s)?(\d{2}):(\d{2})\+(\d{1,2})$/;` или так  `/^(?:(ПН|ВТ|СР)\s)?(\d{2}):(\d{2})\+(\d{1,2})$/;`

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +            this.timezone = timezone;
А почему timezone не приватная, как minutes?

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +                .concat(this._getGangsBusyIntervals(schedule));
Почему bad?
Такой код можно оформлять вот так:
```
this._badIntervals = this
    ._getBankCloseIntervals(workingHours)
    .concat(this._getGangsBusyIntervals(schedule));
```
Я бы правда еще в конкат переменную передавал, а не вызов функции, но тут ок

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +            return busyTimes;
❗️ Давай через `reduce` перепишем

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +                    from = from < to && from > 0 ? from : 0;
❗️ Это зачем? Мы гарантируем правильные даты

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +                    return (interval[0] <= start && start < interval[1]) ||
❗️ Плюсую

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +        value: function (start, duration) {
❗️ Что делает эта функция, почему сюда начало прилетать start+duration вместо принятых везде from+to или объекта Moment?

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +        value: function (start, duration) {
И вообще не понятно, зачем нам эта функция, если у нас уже есть badIntervals. Тем более зачем нам фильтровать эти интервалы, если они "плохие"

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +    moment: {
странное название, темболее у тебя так функция-конструктор называется. Я беру в коде завожу переменную `var moment = new Moment`, а потом начинаю использовать `moment.moment` 😱 
Чем плохо просто minutes? или timestamp? или time?

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +    var robberyMoments = robbery.getMoments(duration);
Вот это выглядит хорошо

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +            while (this._start.moment + duration <= this._deadline.moment) {
❗️ Как-то не оптимально. Если у тебя неделя будет длинyе и duration короче?

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +            while (this._start.moment + duration <= this._deadline.moment) {
❗️ С одной стороны твое апи позволяет попросить моменты для ограбления любой длины и думал что могу несколько раз вызвать данную функцию. А с другой ты портишь `this.start` и второй вызов ничего не даст. Получается, что у тебя одноразовые инстансы и тут возникают вопросы: почему duration не передать в конструктор сразу и, следом, нафига нам инстансы, а не просто одна функция `getMoments(schedule, duration, workingHours)`

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +                    this._start.moment += 30;
❗️ Почему 30 не в "константе"?

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +                    this._start.moment = Math.max.apply(Math, badIntervals);
❗️ Тут тоже не оптимально. Проще их один раз отсортировать.

2016-10-28 03:57 UTC, dzlk commented on robbery.js
> +                    this._start.moment = Math.max.apply(Math, badIntervals);
❗️ Ты уверен что Math.max тут вообще отрабатывает? Если да, то почему?

2016-10-28 03:57 UTC, dzlk commented
🍅

2016-10-28 07:35 UTC, LeMarck commented on robbery.js
> +Object.defineProperties(Moment.prototype, {
На лекции было про ```Object.defineProperties()```, решил использовать.

2016-10-28 07:36 UTC, LeMarck commented on robbery.js
> +    moment: {
```minutes``` - это кол-во минут в часе. ```time``` - время (часы:минуты:секунды). А мне нужно кол-во минут относительно ```ПН 00:00```
Ужасный пример, но - ```time.time()``` https://pythonworld.ru/moduli/modul-time.html

2016-10-28 07:49 UTC, LeMarck commented on robbery.js
> +                    from = from < to && from > 0 ? from : 0;
Как я понял, правильная дата - ```ДЕНЬ часы:минуты+часовой_пояс```. И когда я пытался найти ошибку, почему не могу пройти тесты, то решил, что возможны такие интервалы занятости грабителей как ```{ from: 'ПТ 17:00+5', to: 'ВТ 13:00+5' }```

2016-10-28 07:54 UTC, LeMarck commented on robbery.js
> +        value: function (start, duration) {
Здесь проверяется, то, что предполагаемое начало ограбления(```start```) + время на ограбление (```duration```) не входят в ```this._badIntervals```. Результат - массив с концами таких интервалов, либо пустой массив

2016-10-28 07:57 UTC, LeMarck commented on robbery.js
> +                    this._start.moment += 30;
Упустил этот момент. Поправлю.

2016-10-28 08:07 UTC, LeMarck commented on robbery.js
> +                    this._start.moment = Math.max.apply(Math, badIntervals);
Уверен, иначе не было бы сдвига.
Как альтернатива:
```js
badIntervals.sort(function (a, b) {
    return a < b;
})[0];
```
Либо стоит отсортировать ```this._badIntervals``` относительно ```this._badIntervals[index][1]``` от большего к меньшему

2016-10-28 08:10 UTC, LeMarck commented on robbery.js
> +            while (this._start.moment + duration <= this._deadline.moment) {
Как-то упустил тот момент, что я порчу переменную. Сейчас исправлю.

2016-10-28 08:20 UTC, dzlk commented on robbery.js
> +                    from = from < to && from > 0 ? from : 0;
Да, возможен, ок

2016-10-28 10:16 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-28 10:16 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-10-28 14:45 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-28 14:45 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-10-31 05:46 UTC, dzlk requested changes

2016-10-31 05:46 UTC, dzlk commented on robbery.js
> +Object.defineProperties(Moment.prototype, {
Выглядит лишним

2016-10-31 05:46 UTC, dzlk commented on robbery.js
> +    _timeShift: {
shiftTime тогда

2016-10-31 05:46 UTC, dzlk commented on robbery.js
> +            time = robberyMoments.shift() || oldTime;
Так аккуратнее

``` js
if (robberyMoments.length) { 
    time = robberyMoments.shift()
}
```

2016-10-31 05:46 UTC, dzlk commented on robbery.js
> +                    schedule[name].reduce(function (acc, interval) {
здесь map тогда уж, раз ты concat делаешь

2016-10-31 05:46 UTC, dzlk commented on robbery.js
> +                            from: from < to && from > 0 ? from : 0,
все еще смущает это условие. Зачем проверка с нолем?

2016-10-31 05:46 UTC, dzlk commented on robbery.js
> +                            from: from < to && from > 0 ? from : 0,
У тебя в minutes абсолютные величины, а это значит 'ПН 23:00' будет точно меньше 'ВТ 12:00'
Зачем все-такие проверка  `from < to`

2016-10-31 05:46 UTC, dzlk commented on robbery.js
> +        value: function (start, end) {
а чо сюда не moment прилетает?

2016-10-31 05:46 UTC, dzlk commented on robbery.js
> +                        (start < interval.from && interval.to < end);
❗️ мне кажется можно проще сделать проверку, если идти отпротивного
Рассмотри случаи, когда у тебя могут не пересекаться интервалы?

2016-10-31 05:46 UTC, dzlk commented on robbery.js
> +                            from: from < to && from > 0 ? from : 0,
❗️

2016-10-31 05:46 UTC, dzlk commented on robbery.js
> +                    })[0] || start;
❗️ А если не делать `|| start`?

2016-10-31 05:53 UTC, LeMarck commented on robbery.js
> +                            from: from < to && from > 0 ? from : 0,
Но 'ПТ 12:20' будет больше 'ВТ 12:20', а вдруг грабитель отдыхает с пятницы по вторник?(```ftom < to```)
При переходе на новую тайм зону может случиться так, что "минут" будет минус сколько-то (относительно нуля - 'ПН 00:00' по банковскому времени :smile:). Вторым условием я отбрасываю ненужные минуты

2016-10-31 06:01 UTC, dzlk commented
🍅

2016-10-31 06:55 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-31 06:55 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-10-31 09:38 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-31 09:38 UTC, honest-hrundel commented
@dzlk обрати внимание решено доп. задание

2016-10-31 09:51 UTC, dzlk commented
принято

2016-10-31 09:51 UTC, closed without merging