Роговой Арсений
urfu-2016/javascript-task-3 pull request #23
Opened 2016-10-23 16:15 UTC by mrkvinter

2016-10-23 16:15 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2016-10-26 08:20 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-26 08:20 UTC, honest-hrundel commented
@Lakate обрати внимание решено доп. задание

2016-10-26 08:33 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-26 08:33 UTC, honest-hrundel commented
@Lakate обрати внимание решено доп. задание

2016-10-26 16:49 UTC, Lakate commented
Привет!
Посмотрела твоё решение и немного обескуражена. Видно, что ты умеешь пользоваться функциями JS. И это круто. Но вот сам алгоритм меня очень расстроил. Он совсем неоптимальный. Это сейчас у нас всего 3 бандита, у которых всего 3 дня на ограбление. А давай представим, что это серьезная группировка, собирающаяся на большое ограбление и у них есть 2 недели? Согласись, что проверять поминутно свободны ли все они не очень хорошая идея. 
Попробуй придумать другой алгоритм?

2016-10-26 16:49 UTC, Lakate commented
:tomato:

2016-10-26 16:50 UTC, Lakate commented
Пиши в судак, как поправишь. Я там lakate

2016-10-26 17:04 UTC, Lakate commented on robbery.js
> +        return { from: parseToMinutes(e.from), to: parseToMinutes(e.to) };
Давай писать каждое поле с новой строки, эти 2 секономленые строчки особой оптимизации не дают, а читабельность ухудшают

2016-10-26 17:04 UTC, Lakate commented on robbery.js
> +        Linus: parseInterval(schedule.Linus)
Оочень плохо так привязываться.
Это сейчас у тебя всего три поля в объекте. А если их будет 1000??

2016-10-26 17:04 UTC, Lakate commented on robbery.js
> +            minute++;
Очень грустно(

2016-10-26 17:05 UTC, Lakate commented
🍅

2016-10-26 19:47 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2016-10-27 06:19 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-27 06:52 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-29 08:34 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-29 08:34 UTC, honest-hrundel commented
@Lakate обрати внимание решено доп. задание

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +    return minutesLaterMonday[weekday] + parseGmtToMinutes(parseTime[1]);
давай `parseTime[1]` тоже вынесем в переменную

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +    return parseTimeToMinutes(parseTime[0]) - gmt * MINUTES_IN_HOURS;
аналогично

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +               for (var i = e.from; e.to >= i + duration; i += 30) {
я так понимаю, что здесь `+30` потому что в доп. задании надо найти через полчаса следующее подходящее время? 
Если нет - тогда объясни пожалуйста, что за цифра
Если да, то плохо так делать. Например мы захотим не через полчаса, а через 2 часа, 5 часов. Тебе надо будет вспоминать и искать, где ты это учитываешь. Выноси ее в константу, так будет правильнее

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +            function (e) {
обычно эту строчку `function (e) {` не переносят, а оставляют на той же строке, где объявляется `forEach`, `map`, `reduce` и тд

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +        function (x, y) {
аналогично

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +                timeZoneBank * 60) : '';
60 надо вынести в константу. Не должно быть в коде "волшебных" цифр. Через месяц сложно вспомнить, зачем ты писал так

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +            return this.exists() ? parseTimeTemplate(template, goodTimes[0] +
непонятно, что за `goodTimes[0]`. Тоже лучше вынеси в переменную

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +    minute -= minutesLaterMonday[weekday];
не следует изменять те переменные, которые тебе передают. Ты можешь забыть об этом, и потом воспользоваться ими, но они уже будут изменены. Заведи новую переменную.
Да и само название переменной  плохое. "Минута" - совсем не отражает суть.

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +    return template.replace(/%DD/g, weekday)
давай тут тоже перенесем на новую стоку `replace`, будет красивее

```
return template
    .replace(/%DD/g, weekday)
    .replace(/%HH/g, hours > 9 ? hours : '0' + hours)
    .replace(/%MM/g, minute > 9 ? minute : '0' + minute);
```

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +function getIntervalWorkTimeBank(workingHours) {
`interval` тут лишний

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +    for (var dayWeek = 0; dayWeek < 3; dayWeek++) {
`dayWeek` не отражает суть. Это не день недели, а номер дня недели

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +            .forEach(function (e) {
не нужно выносить это на отдельную строку, если у тебя не несколько таких функций, как например дальше с `replace`

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +            function (a, b) {
отсортируй отдельно, и передавай уже отсортированный массив. Не стоит усложнять код, и делать его менее читабельным

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +function combine(intervals) {
название функции совсем не говорит, что она делает. В идеале, всегда хочется по названию функции понимать, что в ней происходит. Конечно, это возможно не всегда. Но именнно поэтому, мы стараемся разбивать код на более мелкие функции, которые выполняют какуое-то одно логическое действие. 
Переименую пожалуйста

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +    var main = 0;
тоже плохое название. По нему совсем непонятно что это такое и к чему относится. чтобы понять что это, приходится смотреть код дальше и вникать для чего эта переменная вообще нужна

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +function getAllBadActsDay(schedule, workingHours, duration) {
хммм, передавали свободное время, а в функции это стало расписанием..Давай для консистентности будем называть одинаково?

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +            .forEach(function (e) {
и плохое название параметра. Совсем непонятное

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +function subtraction(set, interval) {
1) по названию тоже непонятно что функция делает
2) в названии функций должен быть глагол
3) названия параметров тоже странные. Что за `set`? что в нем хранится?

2016-10-30 16:57 UTC, Lakate commented on robbery.js
> +    var last = set.pop();
последний что? помидор? час? шанс?)

2016-10-30 16:59 UTC, Lakate commented
Уже гораздо лучше, ты молодец, что придумал с интервалами.
Но  расскажи почему ты именно в минуты переводишь все? Ведь из-за этого, тебе нужно делать много вспомогательных действий, чтобы сначала перевести все в минуты, а потом из минут првератить обратно все в часы и дни. Почему не использовать функции `Date`??

поправляй, и пиши в slack

2016-10-30 16:59 UTC, Lakate commented
🍅

2016-10-31 05:51 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-31 05:51 UTC, honest-hrundel commented
@Lakate обрати внимание решено доп. задание

2016-11-03 02:05 UTC, Lakate reviewed
Все-таки мне совсем не нравится эта идея с минутами, из-за нее много лишнего кода.
Я считаю, что правильнее было бы использовать возможности `Date`

2016-11-03 02:05 UTC, Lakate commented on robbery.js
> +        if (combines === null) {
```
if (!combines) {
...
```

2016-11-03 02:05 UTC, Lakate commented on robbery.js
> +
лишняя строка

2016-11-03 02:05 UTC, Lakate commented on robbery.js
> +    var howManyTry = 30;
странное название. Это же просто сдвиг, а не то, что тут написано

2016-11-03 02:06 UTC, Lakate commented
Верю, что эти мелкие замечания поправишь, а про минуты вы еще с ментором обсудите
🚀

2016-11-03 06:39 UTC, hrundik requested changes
🍅

2016-11-03 06:39 UTC, hrundik commented on robbery.js
> +    for (var numberOfDayWeek = 0; numberOfDayWeek < 3; numberOfDayWeek++) {
`3` здесь -- это `magic constant`. Такие вещи нужно выносить в константы с осмысленным именем

2016-11-03 06:39 UTC, hrundik commented on robbery.js
> +function tryCombineIntervals(first, second) {
~~Можно называть покороче: `intersect`~~ А не, это у вас действительно функция объединения.

2016-11-03 06:39 UTC, hrundik commented on robbery.js
> +        if (combines === null) {
+1

2016-11-03 06:39 UTC, hrundik commented on robbery.js
> +    var combineSchedule = combineTimeIntervals(sortIntervals);
`combinedSchedule`. Но я бы это назвал `busyIntervals`

2016-11-03 06:39 UTC, hrundik commented on robbery.js
> +function getAllBadActsDay(schedule, workingHours, duration, howManyTry) {
`howManyTry` -> `attemptOffset`

2016-11-03 06:39 UTC, hrundik commented on robbery.js
> +        isBetween(lastInterval.from, subtractionInterval.to, lastInterval.to))) {
По-моему, тут должно быть `!isBetween(lastInterval.from, subtractionInterval.to, lastInterval.to)`. Но до этого условия не доходит, потому что все busy intervals внутри одного дня.

2016-11-03 06:39 UTC, hrundik commented on robbery.js
> +    }
Попробуйте отсюда вынести метод `substractInterval(first, second):Interval[]`. Сейчас функция длинная и тяжело читается.

2016-11-03 06:41 UTC, hrundik commented
А по поводу минут: в условиях задачи вполне можно оперировать минутами.
Но в реальном мире с реальным расписанием `Date` был бы лучше. Например, из-за корректной обработки переводов часов.

2016-11-03 08:10 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-11-03 08:10 UTC, honest-hrundel commented
@hrundik обрати внимание решено доп. задание

2016-11-03 08:11 UTC, mrkvinter commented
🍏

2016-11-03 08:13 UTC, hrundik commented
@mrkvinter поехали дальше )

2016-11-04 13:00 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-11-04 13:00 UTC, honest-hrundel commented
@hrundik обрати внимание решено доп. задание

2016-11-04 13:01 UTC, closed without merging