Бравилов Николай
urfu-2016/javascript-task-3 pull request #25
Opened 2016-10-23 17:38 UTC by kol9nus

2016-10-23 17:39 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-23 18:44 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-23 18:53 UTC, honest-hrundel commented
@Mokoshka обрати внимание решено доп. задание

2016-10-24 05:49 UTC, Mokoshka commented on robbery.js
> +            var afterNMillisec = 30 * 60000;
Можно вынести как константу и можно записать 60 * 1000, что сразу покажет, откуда взялось это число

2016-10-24 05:49 UTC, Mokoshka commented on robbery.js
> +            if (lastAppropriate.from + afterNMillisec + duration * 60000 <= lastAppropriate.to) {
Тоже константа

2016-10-24 05:52 UTC, Mokoshka commented on robbery.js
> +            if (element.timestamp - lastFoundedElement.timestamp >= duration * 60 * 1000) {
константа

2016-10-24 06:01 UTC, Mokoshka commented on robbery.js
> +            if (element.timestamp - lastFoundedElement.timestamp >= duration * 60 * 1000) {
Условие для if можно переписать используя оператор И, а для улучшения читаемости можно вынести в переменные, например:
`var timeDifference = element.timestamp - lastFoundedElement.timestamp;
if (timeDifference >= duration * 60 * 1000)`

2016-10-24 06:05 UTC, Mokoshka commented on robbery.js
> +var nameByDay = [undefined, 'ВС', 'ПН', 'ВТ', 'СР', 'ЧТ'];
Что за день недели "undefined"?

2016-10-24 06:24 UTC, Mokoshka commented on robbery.js
> +    for (var i = 2; i < keys.length - 1; i++) {
Какое-то неявное объявление периода, может получится переписать этот кусочек кода элегантнее?

2016-10-24 09:13 UTC, Mokoshka commented on robbery.js
> +    var appearances = [false, true, true, true];
Выглядит странно. Для чего нужен этот массив и почему в нем именно такие значения?

2016-10-24 09:17 UTC, Mokoshka commented
🍅

2016-10-24 09:20 UTC, kol9nus commented on robbery.js
> +    var appearances = [false, true, true, true];
Да, за это извиняюсь, думал, что даны времена по условию задачи, в которые грабители МОГУТ грабить банк. Потом дошло, что они в это время ЗАНЯТЫ. Идея была, что если все 3 грабителя и банк на временной шкале встретились нечётное ко-во раз (0 чётное, значит false изначально), то это подходящее время для ограбления (не учитывая длительность). Но так как они не могут в это время, то и времена грабителей должны встретиться чётное кол-во раз (т.е. изначально true т.к. 0 чётное). Надо поправить как-нибудь..

2016-10-24 09:23 UTC, kol9nus commented on robbery.js
> +            var afterNMillisec = 30 * 60000;
Для константы имя не могу подходящее придумать.. С одной стороны нужно дать достаточно чёткое название, с другой стороны не сильно длинное, с третьей нельзя сокращать.
Единственное, что приходит на ум HALF_HOUR_MILLISECONDS или, если пренебречь "третью сторону", HALF_HOUR_MILLISEC или HALF_HOUR_MS.

2016-10-24 09:25 UTC, kol9nus commented on robbery.js
> +            if (element.timestamp - lastFoundedElement.timestamp >= duration * 60 * 1000) {
Была такая идея, но так и не придумал подходящего названия для timeDifference. При условии, что мы будем использовать его только в этом условии, смысл достаточно понятен, но если использовать его дальше, смысл потеряется

2016-10-24 10:11 UTC, Mokoshka commented on robbery.js
> +            if (element.timestamp - lastFoundedElement.timestamp >= duration * 60 * 1000) {
Но ты используешь это значение в этой функции только один раз)

2016-10-24 10:53 UTC, kol9nus commented on robbery.js
> +            if (lastAppropriate.from + afterNMillisec + duration * 60000 <= lastAppropriate.to) {
Как она может быть константой, если она зависит от входных данных? Т.е. как это лучше реализовать, как константу, которая при запуске getAppropriateMoment меняется или константу внутри функцию getAppropriateMoment или просто переменную в данной функции?

2016-10-24 11:43 UTC, Mokoshka commented on robbery.js
> +            if (lastAppropriate.from + afterNMillisec + duration * 60000 <= lastAppropriate.to) {
"60000" - константа

2016-10-24 12:56 UTC, kol9nus commented on robbery.js
> +            if (element.timestamp - lastFoundedElement.timestamp >= duration * 60 * 1000) {
Ах, да, если переписать If используя И и вынести в переменные, как ты написала, то переменная будет пересчитываться каждый раз, хотя она не всегда нужна

2016-10-24 13:12 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-24 13:12 UTC, honest-hrundel commented
@Mokoshka обрати внимание решено доп. задание

2016-10-24 17:07 UTC, Mokoshka commented on robbery.js
> +    for (var i = 0; i < keys.length; i++) {
Уже получше, только пожалуй это не keys, надо как-то по-другому назвать.

2016-10-24 17:08 UTC, Mokoshka commented on robbery.js
> +    for (var i = 0; i < keys.length; i++) {
А почему ты не используешь forEach здесь?

2016-10-24 17:11 UTC, kol9nus commented on robbery.js
> +    for (var i = 0; i < keys.length; i++) {
Честно говоря, просто не знаю, что лучше. forEach выглядит куда более привлекательно, хотя for работает быстрее (может просто заблуждение). А что лучше использовать? И как выбирать?

2016-10-24 17:45 UTC, Mokoshka commented on robbery.js
> +function tryLaterInNextPeriods(o) {
Плохое название аргумента у функции. И она работает с объектом, может тогда сделать ее приватным методом этого объекта?

2016-10-24 17:49 UTC, Mokoshka commented on robbery.js
> +    }
Ты записываешь значение в переменную i и сразу же инкриментируешь ее. Кажется, будет лучше, сразу же присвоить нужное значение. А в цикле ты два раза увеличиваешь индекс на единицу, можно сначала увеличить, а потом проверять условие.

2016-10-24 18:03 UTC, Mokoshka commented on robbery.js
> +                    }
Можно записать 
```
appropriateMoments.push({
    from: lastFoundedElement.timestamp,
    to: element.timestamp
})
```

2016-10-24 18:14 UTC, Mokoshka commented on robbery.js
> +    timeLine.forEach(function (element) {
Неудачное название переменной, непонятно что за элемент

2016-10-24 18:17 UTC, Mokoshka commented on robbery.js
> +    Object.keys(schedule).forEach(function (key, index) {
Неудачное название переменной key. Старайся называть перменные так, чтобы их название отображало то, что они в себе содержат

2016-10-24 18:38 UTC, Mokoshka commented on robbery.js
> +    for (var i = 0; i < keys.length; i++) {
Разницы в скоростях на таких объемах данных нет. ForEach выглядит аккуратнее, можно забыть про индексы и работать только с текущим объектом. Как по мне, то так код становится намного читабельнее

2016-10-24 18:38 UTC, Mokoshka commented
🍅

2016-10-25 04:57 UTC, kol9nus commented on robbery.js
> +function tryLaterInNextPeriods(o) {
А это возможно сделать в текущей реализации, или возможно только создать объект и с помощью defineProperty создавать приватный метод?

2016-10-25 05:36 UTC, kol9nus commented on robbery.js
> +function tryLaterInNextPeriods(o) {
Или достаточно добавить _ вначале названия функции?

2016-10-25 06:39 UTC, Mokoshka commented on robbery.js
> +function tryLaterInNextPeriods(o) {
Достаточно добавить _

2016-10-25 09:21 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-25 09:21 UTC, honest-hrundel commented
@Mokoshka обрати внимание решено доп. задание

2016-10-25 12:30 UTC, Mokoshka commented on robbery.js
> +                : '';
👍

2016-10-25 12:33 UTC, Mokoshka commented on robbery.js
> +            var i = this._lastIndex + 1;
this._lastIndex + 1  можно вынести в переменную перед if

2016-10-25 12:34 UTC, Mokoshka commented on robbery.js
> +    ['ПН', 'ВТ', 'СР'].forEach(function (day) {
Вынести бы еще этот массив как константу - вообще шик будет

2016-10-25 12:36 UTC, kol9nus commented on robbery.js
> +    ['ПН', 'ВТ', 'СР'].forEach(function (day) {
А оно надо? Он же используется один раз в одном месте..

2016-10-25 12:39 UTC, Mokoshka commented on robbery.js
> +    ['ПН', 'ВТ', 'СР'].forEach(function (day) {
Если посмотреть в условие задачи, то этот период зафиксирован, поэтому сильно напоминает константу. И на будущее, если так случится, что подобные значения нужно будет изменить, то найти их в начале файла по названию гораздо проще, чем искать где-то в коде)

2016-10-25 12:40 UTC, Mokoshka commented
🚀

2016-10-25 12:58 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-25 12:58 UTC, honest-hrundel commented
@mokhov обрати внимание решено доп. задание

2016-10-26 05:31 UTC, mokhov commented
🍅  посмотрю ещё днём уже сам алгоритм, есть ощущение что он не оптимален

2016-10-26 05:31 UTC, mokhov commented on robbery.js
> +var timePattern = /^(?:([a-zа-я]{2}) )?(\d\d):(\d\d)\+(\d+)$/i;
Зачем a-z?

2016-10-26 05:31 UTC, mokhov commented on robbery.js
> +var timePattern = /^(?:([a-zа-я]{2}) )?(\d\d):(\d\d)\+(\d+)$/i;
`\d\d` === `\d{2}`

2016-10-26 05:31 UTC, mokhov commented on robbery.js
> +var timePattern = /^(?:([a-zа-я]{2}) )?(\d\d):(\d\d)\+(\d+)$/i;
Пробел обычно \s обозначается

2016-10-26 05:31 UTC, mokhov commented on robbery.js
> +var BANK_WORKDAYS = ['ПН', 'ВТ', 'СР'];
Этот массив можно сделать slice'ом из другого массива

2016-10-26 05:31 UTC, mokhov commented on robbery.js
> +var nameByDay = ['ВС', 'ПН', 'ВТ', 'СР', 'ЧТ'];
Это ключи массива `dayByName`

2016-10-26 05:31 UTC, mokhov commented on robbery.js
> +var M_TO_MS_MULTIPLIER = 60 * 1000;
Зачем это странное название, если можно просто `MINUTE`

2016-10-26 05:31 UTC, mokhov commented on robbery.js
> +        if (availabilities.every(isTrue)) {
Конструктор Boolean, если вызвать его без new, будет делать то же самое

2016-10-26 05:31 UTC, mokhov commented on robbery.js
> +                timestamp: parseTime(day + ' ' + workingHours.from),
Абсолютно не понятно зачем собирать строку, чтобы потом её же разобрать в `parseTime` регуляркой

2016-10-26 05:31 UTC, mokhov commented on robbery.js
> +        schedule[person].forEach(function (time) {
Есть такой принцип DRY – don't repeat yourself. Здесь ты его нарушаешь и повторяешь себя в строчках 141-152

2016-10-26 05:59 UTC, kol9nus commented on robbery.js
> +var BANK_WORKDAYS = ['ПН', 'ВТ', 'СР'];
А в чём преимущества создавать константы из других? Просто, если у нас поменяются массив дней каким-либо образом, то и slice придётся менять (Они же логикой никак не связаны).

2016-10-26 07:06 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-26 07:06 UTC, honest-hrundel commented
@mokhov обрати внимание решено доп. задание

2016-10-26 08:34 UTC, mokhov commented on robbery.js
> +var BANK_WORKDAYS = ['ПН', 'ВТ', 'СР'];
С чего это вдруг? Завтра ты переходишь на английские дни. В твоём случае ты меняешь две строчки, в моём случае – одну

2016-10-26 09:10 UTC, mokhov requested changes
Посмотрел по алгоритму, есть замечания 🍅

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> +        _tryLaterInSamePeriod: function () {
Плохо называть функцию «try», если результат работы функции – Boolean. Чаще всего название функции должно быть вопросом с ответом «да/не», а такие вопросы начинаются с `is`

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> +    return number < 10 ? '0' + number : number.toString();
`return (number < 10 ? '0' : '') + number`, а вообще `return ('0' + number).slice(-2)`

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> +var timePattern = /^(?:([а-я]{2})\s)?(\d{2}):(\d{2})\+(\d+)$/i;
Зачем тут столько скобочек? и зачем нужно не захватывающее соответствие «?:»

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> +        _appropriatePeriods: defineAppropriatePeriods(timeline, duration),
Непонятно чем обуславливается выбор в одном случае в пользу переменной, которая в замыкании `timeline`, а в другом случае псевдоприватным полем

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> + * Алгоритм получения подходящего времени следующий: сначала выстраиваем все времена участников и
В целом алгоритм забавный, но жаль что его легко сломать неверными данными. Т.е ты полагаешься изначально на гипотезу, что тебе прислали непересекающиеся интервалы в расписании. А если вдруг какой-нибудь Вася тебе пришлет интервалы (условно): `[ [ 10, 13], [12, 14] ]`? То всё, алгоритм ломается :( Это комментарии не про то что надо переписать алгоритм, а про то что будь на чеку в целом и проверяй входные данные

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> +            if (timeForRobbing >= duration * MINUTE_MS) {
Это умножение можно не делать каждый раз, а вынести его в переменную

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> +        if (availabilities.every(Boolean)) {
Можно объединить это с условием внутри, т.е написать здесь

``` javascript
if (availabilities.every(Boolean) && 
    time.timestamp - lastFoundedTime.timestamp >= robberyDuration)
```

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> +        if (availabilities.every(Boolean)) {
Тогда пропадет один уровень вложенности и код станет чище

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> +function defineAppropriatePeriods(timeline, duration) {
Очень хочется в этой функции избавиться от лишних операций, например, если `availabilities = [false, true, false, true]`, то следующая операция приведет массив в состояние, при котором 100% не может быть ограбления, т.е как минимум на каждом втором шаге цикла можно не выполнять проверку `availabilities.every(Boolean)`. Подумай как ещё можно ускориться

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> +    var day = nameByDay[temp];
`var day = nameByDay(date.getUTCDate())`

2016-10-26 09:10 UTC, mokhov commented on robbery.js
> +        lastFoundedTime = time;
find – неправильный глагол ;) А found – это «основывать», поэтому тут получилось «последнее основанное время»

2016-10-26 11:20 UTC, kol9nus commented on robbery.js
> +var timePattern = /^(?:([а-я]{2})\s)?(\d{2}):(\d{2})\+(\d+)$/i;
Скобочки для разбивки и вычленения определённых частей при парсе (все группы в скобочках). А не захватывающее нужно, т.к. дня может не быть (у времени работы банка, например), а всё парсится с помощью этого паттерна. Не захватывающее потому, что зачем нам лишняя группа?

2016-10-26 11:22 UTC, kol9nus commented on robbery.js
> + * Алгоритм получения подходящего времени следующий: сначала выстраиваем все времена участников и
Да, очень хорошее замечание. Спасибо.

2016-10-26 11:26 UTC, kol9nus commented on robbery.js
> +        _appropriatePeriods: defineAppropriatePeriods(timeline, duration),
Данная конструкция объекта у меня ассоциируется с классом, и, раз все функции "класса" работают с appropriatePeriods, было бы логично сделать его "членом класса". А timeline "временная" переменная для подсчёта appropriatePeriods. И да. Для меня, честно говоря, какая то магия происходит в том, что мы можем получать доступ к timeline извне, при условии, что она в функции, а не в возвращаемом объекте.

2016-10-26 11:30 UTC, kol9nus commented on robbery.js
> +        _tryLaterInSamePeriod: function () {
Проблема в том, что функция is не подразумевает изменение переменных "класса", а это происходит. С этой точки зрения, try звучит менее обязывающей + воспользовался тем, что в условии задачи функция с похожим функционалом названа tryLater, а это, якобы, её "наследники".

2016-10-26 11:52 UTC, mokhov commented on robbery.js
> +        _tryLaterInSamePeriod: function () {
В таких случаях начинают с `can` что-нибудь типа «можем ли попробовать позже»

2016-10-26 11:53 UTC, mokhov commented on robbery.js
> +var timePattern = /^(?:([а-я]{2})\s)?(\d{2}):(\d{2})\+(\d+)$/i;
Хороший ответ, не заметил что ты эту регулярку в двух местах используешь! 👍

2016-10-26 11:54 UTC, mokhov commented on robbery.js
> +        _appropriatePeriods: defineAppropriatePeriods(timeline, duration),
Ну с `this` там не меньшая магия будет тоже. Но ладно, давай в этой задаче оставим так как есть, ответ принимаю

2016-10-26 12:21 UTC, kol9nus commented on robbery.js
> +    return number < 10 ? '0' + number : number.toString();
Слишком круто

2016-10-26 12:36 UTC, kol9nus commented on robbery.js
> +function defineAppropriatePeriods(timeline, duration) {
Придумал использовать битовые операции и Int, вместо массива. Например, есть переменная size = 0001 (в двоичном представлении) изначально. Изменяем её size ^= 1 << time.id, и, когда она будет равна 0, ограбление возможно. Но битовые операции запрещены eslint

2016-10-26 13:35 UTC, mokhov commented on robbery.js
> +function defineAppropriatePeriods(timeline, duration) {
Да, молодец, именно этого я и хотел. Убери конкретно здесь это ограничение ESLint

2016-10-27 08:37 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-27 08:37 UTC, honest-hrundel commented
@mokhov обрати внимание решено доп. задание

2016-10-27 08:45 UTC, mokhov commented
Красота! Принято

2016-10-27 08:45 UTC, closed without merging