Свалова Настя
urfu-2016/javascript-task-3 pull request #27
Opened 2016-10-23 19:59 UTC by SvalovaNastya

2016-10-23 19:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-23 20:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-23 20:16 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2016-10-23 20:25 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 19

2016-10-23 20:47 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 19

2016-10-23 20:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 19

2016-10-23 21:01 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 19

2016-10-24 17:36 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-24 18:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-24 19:22 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-24 20:16 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 19

2016-10-26 06:03 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-26 06:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-26 06:31 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-26 06:41 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-26 06:55 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-26 09:28 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-26 17:26 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-26 17:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-26 17:57 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-26 18:05 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-26 18:06 UTC, honest-hrundel commented
@Dotokoto обрати внимание решено доп. задание

2016-10-27 18:05 UTC, Dotokoto commented on robbery.js
> +    return 3 * MINUTES_IN_DAY - bankTimeZone * MINUTES_IN_HOUR - 1;
3 - это ведь тоже константа, нужно вынести

2016-10-27 18:08 UTC, Dotokoto commented on robbery.js
> +
Если в функции только один return, то перед ним пустая строка не нужна

2016-10-27 18:12 UTC, Dotokoto commented on robbery.js
> +
Не нужно столько пустых строк. Стоит отделять строкой блок объявления переменных от действий, или логические блоки. А объявления переменных вполне можно подряд в каждой строке писать

2016-10-27 18:16 UTC, Dotokoto commented on robbery.js
> +                ? getFormatData(timeForRobbery[currentTimeForRobbery], template, bankTimeZone)
Слишком много логических условий в одной строке, это запутывает. Давай разнесем
```javascript
if (!timeForRobbery.length || !template) {
    return '';
}
return getFormatData(...);
```

2016-10-27 18:18 UTC, Dotokoto commented on robbery.js
> +            if (timeForRobbery.length <= 0) {
А длина массива может быть меньше 0? ) Можно просто проверять ``` if(!timeForRobbery.length)```

2016-10-27 18:24 UTC, dotokoto commented on robbery.js
> +    return parseInt(timeZoneGroups[1]);
У parseInt надо всегда указывать второй аргумент - систему счисления. [Здесь можно почитать подробнее](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/parseInt). Иначе, например, начинающиеся с 0 числа могут быть восприняты как 8-ричные.

2016-10-27 18:31 UTC, dotokoto commented on robbery.js
> +    for (var manScheduleKey in schedule) {
Мне кажется, здесь удобнее использовать Object.keys(schedule). Тогда не нужно будет проверять hasOwnProperty.

2016-10-27 18:35 UTC, Dotokoto commented on robbery.js
> +        busyIntervals.push(
Менять переданный в функцию массив или объект, да и вообще аргументы - чаще всего плохая идея. Давай переименуем функцию в getInterval, будем возвращать из нее объект. А складывать объекты в массив - там, где функция вызывается.

2016-10-27 18:38 UTC, Dotokoto commented on robbery.js
> +        parseInt(timeGroups[2]) * MINUTES_IN_HOUR +
см. замечание выше про parseInt

2016-10-27 18:42 UTC, Dotokoto commented on robbery.js
> +        for (var i = 0; i < manSchedule.length; i++) {
Можно переписать как 
```javascript
manSchedule.forEach(function (interval) {
    ...
});
```
Это не обязательно, но forEach более в "джаваскриптовом" стиле :)

2016-10-27 18:48 UTC, Dotokoto commented on robbery.js
> +            }, busyIntervals);
```javascript
addInterval(
    {
        from: ...,
        to: ...
    },
    busyIntervals
);
```
Чтобы взглядом было легче отделять каждый параметр и конец вызова функции

2016-10-27 18:48 UTC, Dotokoto commented on robbery.js
> +    return busyIntervals;
return busyIntervals.sort(sortIntervals);

2016-10-27 18:54 UTC, Dotokoto commented on robbery.js
> +    while (currentTime <= getEndTimeOfRobbery(bankTimeZone) &&
getEndTimeOfRobbery(bankTimeZone) вынеси в переменную, иначе функция каждый раз в цикле вызывается

2016-10-27 18:56 UTC, Dotokoto commented on robbery.js
> +    var currentInterval = 0;
это currentIntervalIndex, а не сам currentInterval

2016-10-27 18:58 UTC, dotokoto commented on robbery.js
> +        if (busyIntervals[currentInterval].from - currentTime >= duration) {
Тут не может возникнуть проблем из-за того, что currentTime у тебя сначала отрицательный, а потом может стать положительным? 
Может перевести время так, чтобы currentTime всегда было >=0? Всё-таки отрицательное текущее время - это странно

2016-10-27 19:01 UTC, Dotokoto commented on robbery.js
> +            currentTime = Math.max(busyIntervals[currentInterval].to, currentTime);
busyIntervals[currentInterval] можно вынести в переменную

2016-10-27 19:05 UTC, dotokoto commented on robbery.js
> +function getFormatData(time, template, bankTimeZone) {
Кажется, эта функция делает две вещи:
1) Получает день, часы и минуты
2) Форматирует строку
А в идеале каждая функция должна делать одну вещь. Стоит разбить на две.

2016-10-27 19:08 UTC, Dotokoto commented
:tomato: Привет! Я посмотрела твое решение. Пока есть замечания, жду правок и буду смотреть еще раз.
Можешь написать мне в Slack, когда поправишь (там у меня такой же ник, @dotokoto). Там я быстрее увижу, чем в почте

2016-10-28 09:41 UTC, SvalovaNastya commented on robbery.js
> +                ? getFormatData(timeForRobbery[currentTimeForRobbery], template, bankTimeZone)
Написан же тернарный оператор, условие, если да, если нет, написаны каждый в своей строчке. По-моему выглядит понятно и кратко. Наоборот нет кучи ветвлений.

2016-10-28 10:09 UTC, SvalovaNastya commented on robbery.js
> +        if (busyIntervals[currentInterval].from - currentTime >= duration) {
Проблем точно нет, я проверяла :) А переводить - слишком много надо будет делать. Мне кажется, что это нормально.

2016-10-28 10:18 UTC, SvalovaNastya commented on robbery.js
> +    for (var manScheduleKey in schedule) {
А есть такая же классная штука не для ключей, а для значений?

2016-10-28 10:34 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-28 10:34 UTC, honest-hrundel commented
@Dotokoto обрати внимание решено доп. задание

2016-10-28 10:44 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-28 10:44 UTC, honest-hrundel commented
@Dotokoto обрати внимание решено доп. задание

2016-10-28 10:46 UTC, SvalovaNastya commented
Неочевидное изменение. Раньше проверялось, что отрезки ненулевые и левый конец строго меньше, чем правый. Теперь из-за предложения не изменять неочевидным образом объект внутри функции пришлось отказаться от этого, иначе привело бы к громоздкости кода, а эта функция итак уже огромная. В условии сказано, что интервалы проверять не надо, но хотелось бы все равно это обсудить.

2016-10-30 15:30 UTC, Dotokoto commented on robbery.js
> +    for (var manScheduleKey in schedule) {
К сожалению, такой штуки нет :(

2016-10-30 15:37 UTC, Dotokoto commented on robbery.js
> +    for (var weekday = 0; weekday < WEEKDAYS_MAP.length - 1; weekday++) {
Можно сделать цикл до DAYS_FOR_ROBBERY, остальные интервалы все равно не понадобятся

2016-10-30 15:39 UTC, Dotokoto commented on robbery.js
> +    busyIntervals.push(getInterval(startIntervalForBank, busyIntervals));
Функция getInterval теперь один параметр принимает, а передаешь все еще два

2016-10-30 15:39 UTC, dotokoto commented on robbery.js
> +            getTimeIntervalForBank(weekday, workingHours), busyIntervals)
То же самое, у getInterval 1 аргумент

2016-10-30 15:47 UTC, Dotokoto commented on robbery.js
> +            return timeForRobbery.length > 0 && template
Можно вместо ```timeForRobbery.length > 0``` писать ```timeForRobbery.length``` , к булевому типу автоматически преобразуется

2016-10-30 15:51 UTC, SvalovaNastya commented on robbery.js
> +            return timeForRobbery.length > 0 && template
Это же не очевидно. По-моему, так лучше...

2016-10-30 15:52 UTC, Dotokoto commented on robbery.js
> +function toTwoFormatString(time) {
Название странное. Как будто эта функция превращает время в две строки. Хотя на самом деле она добавляет ведущий ноль, если он нужен

2016-10-30 15:54 UTC, Dotokoto commented on robbery.js
> +    formatString += time.toString();
При сложении со строкой число автоматически преобразуется к строке, можно не делать toString

2016-10-30 15:57 UTC, Dotokoto commented on robbery.js
> +    formatString += time.toString();
Вообще, всю функцию можно короче записать:
```javascript
if (time < 10) {
    return '0' + time;
}
return time;
```

2016-10-30 15:57 UTC, Dotokoto commented on robbery.js
> +    var formatString = template.replace('%HH', toTwoFormatString(timeObject.hours.toString()))
toString() не нужен, число само преобразуется к строке

2016-10-30 15:58 UTC, Dotokoto commented on robbery.js
> +    var currentTimeForRobbery = 0;
Это не текущее время, а текущий индекс в массиве

2016-10-30 16:11 UTC, dotokoto commented on robbery.js
> +function prepareTimeIntervals(schedule, workingHours, bankTimeZone) {
Эта функция вышла достаточно большая. В принципе, не критично. Но можно выделить две функции: получение интервалов для грабителей и интервалов для банка. А потом объединить два массива

2016-10-30 16:15 UTC, Dotokoto commented
:tomato: Посмотрела еще раз, остались только небольшие замечания. Давай еще немного поправим, и будет совсем хорошо )
По поводу проверки валидности интервалов: сейчас добавлять ее не нужно. Но вообще, можно было бы проверять в getInterval. И если интервал не валиден, то вместо объекта возвращать null. А в массив пушить, только когда вернулся не null.

2016-10-30 16:17 UTC, Dotokoto commented on robbery.js
> +            return timeForRobbery.length > 0 && template
Это общепринятое сокращение в javascript, оно очень часто встречается

2016-10-30 16:30 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-30 16:30 UTC, honest-hrundel commented
@Dotokoto обрати внимание решено доп. задание

2016-10-30 17:21 UTC, Dotokoto commented
Оставляй, пожалуйста, комментарий с эмодзи зеленого яблочка [(здесь написано, как)](https://github.com/urfu-2016/guides/blob/master/workflow/overall.md), когда готова показывать исправления. Иначе мне на почту не приходит никаких уведомлений :(

2016-10-30 17:23 UTC, Dotokoto commented
:rocket:

2016-10-30 18:14 UTC, mokhov requested changes
Код хороший, но можно сделать его ещё лучше. Давай попробуем? 🍅

2016-10-30 18:14 UTC, mokhov commented on robbery.js
> +    var timeRegex = /([А-Яа-я]{2}) (\d{2}):(\d{2})\+(\d+)/;
Маленькие буквы для перестраховки?

2016-10-30 18:14 UTC, mokhov commented on robbery.js
> +    if (a.from > b.from) {
Всё можно сделать короче

2016-10-30 18:14 UTC, mokhov commented on robbery.js
> +            currentTime += 30;
Почему именно такой шаг?

2016-10-31 13:23 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-31 13:23 UTC, honest-hrundel commented
@mokhov обрати внимание решено доп. задание

2016-10-31 13:26 UTC, SvalovaNastya commented
:green_apple:

2016-11-02 09:24 UTC, closed without merging