Мозалов Павел
urfu-2016/javascript-task-3 pull request #28
Opened 2016-10-23 20:36 UTC by MozalovPavel

2016-10-23 20:37 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 19

2016-10-23 21:47 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-24 17:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-24 19:35 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-24 20:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-24 20:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-24 21:35 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-24 21:38 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-24 21:39 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-24 21:41 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-24 22:15 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-24 22:15 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-25 07:59 UTC, m1ralx reviewed
WIP

2016-10-25 07:59 UTC, m1ralx commented on robbery.js
> +    'ПН': 10,
Почему именно эти числа?

2016-10-25 07:59 UTC, m1ralx commented on robbery.js
> +var LEFT_BORDER = new Date(CONST_YEAR, CONST_MONTH, WEEK_DAYS_DICTIONARY['ПН'], 0, 0);
Может быть придумать название, которое лучше отображает условие задачи? Я к тому, что в условии нет никаких `LEFT_BORDER`

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
>  exports.getAppropriateMoment = function (schedule, duration, workingHours) {
Этот метод можно и нужно декомпозировать

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
> +        workingHours.from.match(/\+(\d{1,2})/)[1]);
кажется, это можно вынести в отдельное и более осмысленно действие

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
> +        .concat(getBankRelaxTime(workingHours))
банк отдыхает и релаксирует? Можно назвать получше

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
> +        var firstInterval = clone(intersectionIntervals[i]);
Wat? Непонятно зачем в этой задаче вообще что-то клонировать

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
> +            from: addMinuteToDate(firstInterval.to, + 1),
что такое `, + 1`? И зачем это тут?

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
> +    var findedMoments = [];
прям `finded`?

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
>      return {
в общем этот метод делает слишком много всего. Нужно разбить его на несколько методов с говорящими названиями

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
> +function getFindedMoment(intervals, duration) {
не очень хорошо использовать функции, меняющие объекты, которые им дали на вход и вообще создающие какие-то сайд-эффекты

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
> +function clone(obj) {
эту задачу точно можно решить без таких костылей

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
> +    'ПН': 10,
Кстати, `_DICTIONARY` в названии скорее лишнее

2016-10-25 07:59 UTC, mironov-alexey commented on robbery.js
> +function intersectionTimeIntervals(intervals) {
Эту и следующую функцию обязательно нужно декомпозировать. Они занимают по 25-35 строк и их невозможно прочитать.

2016-10-25 07:59 UTC, mironov-alexey commented
:tomato:

2016-10-25 09:36 UTC, m1ralx commented on robbery.js
> +            if (!lastMoment) {
``` javascript
return foundMoments.length !== 0;
```

?

2016-10-27 13:05 UTC, mironov-alexey commented
@MozalovPavel ping

2016-10-27 19:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 16 из 19

2016-10-27 19:43 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 19

2016-10-27 20:15 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-27 20:21 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 16

2016-10-27 20:24 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-27 20:24 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-27 20:32 UTC, MozalovPavel commented
:green_apple:

2016-10-28 14:14 UTC, m1ralx requested changes
bump

2016-10-28 14:14 UTC, m1ralx commented on robbery.js
> +var TODAY = new Date();
👍

2016-10-28 14:14 UTC, m1ralx commented on robbery.js
> +    WEEK_DAYS['ПН'], 0, 0).getTime();
тут можно не упарываться так, а просто поставить единичку, а можно и так оставить -- как хочешь.

2016-10-28 14:14 UTC, m1ralx commented on robbery.js
> +    timeIntervals = timeIntervals.concat([
можно юзать `push` и указывать интервалы через запятую :)

2016-10-28 14:14 UTC, m1ralx commented on robbery.js
> +    timeIntervals = timeIntervals.concat([
кстати, зачем тут два интервала нулевой длины-то?

2016-10-28 14:14 UTC, m1ralx commented on robbery.js
> +            var textDay = weekDays.filter(function (weekDay) {
можно прям в одну строчку `Object.keys(...`

2016-10-28 14:14 UTC, m1ralx commented on robbery.js
> +            var textDay = weekDays.filter(function (weekDay) {
так тоже будет норм

2016-10-28 14:14 UTC, m1ralx commented on robbery.js
> +                    to: lastMoment + 29 * MS_IN_MIN
Magic constanc `29`? Можно вынести в переменную же хотя бы

2016-10-28 14:14 UTC, mironov-alexey commented on robbery.js
> +            timeIntervals = intersectionTimeIntervals(timeIntervals);
где-то раньше уже была такая строчка и она тоже шла перед вызовом `getRobberyMoment`. Можно наверное это действие прям там и делать.

2016-10-28 14:14 UTC, mironov-alexey commented on robbery.js
> +            if (lastTruMoment === lastMoment) {
что значит `Tru`?

2016-10-28 14:14 UTC, mironov-alexey commented on robbery.js
> +    var deltaZone = templateTimezone - interval.timezone;
что за шаблонная таймзона?

2016-10-28 14:14 UTC, mironov-alexey commented on robbery.js
> +    var matches = timeString.match(/^([А-Я]{2})\s(\d{2}):(\d{2})/);
`parsedTime` можно назвать, например

2016-10-28 14:14 UTC, mironov-alexey commented on robbery.js
> +    var date = new Date(TODAY.getFullYear(), TODAY.getMonth(), day, hours, minutes).getTime();
можно прям тут `return ..`

2016-10-28 14:14 UTC, mironov-alexey commented on robbery.js
> +    return null;
если этой строчки не будет, код перестанет работать?

2016-10-28 14:14 UTC, mironov-alexey commented on robbery.js
> +    while (firstInterval.to !== intervals[intervals.length - 1].to &&
сложное условие, (ещё и в одну строчку не влезает) проверку которого можно вынести в осмысленно названную функцию

2016-10-28 14:14 UTC, mironov-alexey commented on robbery.js
> +        if (firstInterval.to >= secondInterval.from && firstInterval.to <= secondInterval.to) {
то же самое, что в предыдущем комменте

2016-10-28 14:14 UTC, mironov-alexey commented on robbery.js
> +        } else if (firstInterval.to >= BEGIN_MONDAY - MS_IN_MIN &&
и ещё раз

2016-10-28 14:14 UTC, mironov-alexey commented on robbery.js
> +function getBankNotWorkingTime(workingHours) {
~~тут просто какой-то ад~~ слишком большая функция на 30+ строк. Старайся использовать компактные функции. Чем меньше функция -- тем проще её читать и тестировать. Точно так же с конструкциями `if..else` -- чем их больше в функции, тем сложнее её тестировать.

2016-10-28 14:14 UTC, mironov-alexey commented
:tomato:

2016-10-28 19:41 UTC, MozalovPavel commented on robbery.js
> +    timeIntervals = timeIntervals.concat([
Вся суть не в нулевой длине, а в том, что есть края. Нужно для того, чтобы не упустить случаи, когда искомые интервалы будут перед краем.

2016-10-28 19:44 UTC, MozalovPavel commented on robbery.js
> +            if (lastTruMoment === lastMoment) {
Опечатка. Должно быть Try.

2016-10-28 19:45 UTC, MozalovPavel commented on robbery.js
> +    return null;
Будет. Решил явно возвращать null)

2016-10-28 21:27 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-28 21:29 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-28 21:29 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-28 21:30 UTC, MozalovPavel commented
:green_apple:

2016-10-29 03:26 UTC, m1ralx requested changes
ещё немножк

2016-10-29 03:26 UTC, mironov-alexey commented on robbery.js
> +    return parseInt(timeString.match(/\+(\d{1,2})$/)[1]);
система счисления вторым аргументом нужна

2016-10-29 03:26 UTC, mironov-alexey commented on robbery.js
> +            if (getRobberyMoment(timeIntervals, duration)) {
тут два вызова `getRobberyMoment` с одними и теми же параметрами. Во-первых, можно обойтись одним. Во-вторых было бы неплохо предпосчитать сразу все подходящие интервалы и тут уже только брать первый подходящий

2016-10-29 03:26 UTC, mironov-alexey commented
🍅

2016-10-29 11:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-29 11:09 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-29 11:09 UTC, MozalovPavel commented
:green_apple:

2016-10-29 11:18 UTC, mironov-alexey commented on robbery.js
> +        foundMoment = getRobberyMoment(timeIntervals, duration);
можно назвать функцию `getRobberyMoments` и найти сразу все подходящие интервалы? Ну и сейчас у тебя между прочим на каждый вызов этой функции сортируется массив с интервалами 😞

2016-10-29 11:18 UTC, mironov-alexey commented
🍅

2016-10-29 11:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-29 11:59 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-29 12:00 UTC, MozalovPavel commented
:green_apple:

2016-10-29 12:09 UTC, mironov-alexey commented on robbery.js
> +function getDurationInterval(interval, duration) {
если тут не используется `interval.from`, то можно передавать сюда только точку, которая используется как начало

2016-10-29 12:10 UTC, mironov-alexey commented
🍅

2016-10-29 12:16 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-29 12:16 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-29 12:17 UTC, MozalovPavel commented
:green_apple:

2016-10-29 12:24 UTC, m1ralx commented on robbery.js
> +            firstInterval = {
тогда это переопределение теряет смысл. Можно взять только то, что у него в `to` и передать в функцию (лучше сначала записать в переменную с осмысленным названием).

2016-10-29 19:34 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-29 19:34 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-29 19:34 UTC, MozalovPavel commented
:green_apple:

2016-10-29 20:12 UTC, mironov-alexey commented
🚀

2016-10-31 12:47 UTC, MozalovPavel commented
:green_apple:

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +    var parsedTime = timeString.match(/^([А-Я]{2})\s(\d{2}):(\d{2})/);
`А-Я` – избыточно, тебе могут прийти только конкретны значения

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +    return parseInt(timeString.match(/\+(\d{1,2})$/)[1], 10);
Здесь можно без регулярного выражения `parseInt(timeString.split('+')[1])`. 

Как общее правило, лучше ими не злоупотреблять и
по возможности обходится простыми методами.

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +    return new Date(TODAY.getFullYear(), TODAY.getMonth(), day, hours, minutes).getTime();
👍

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +    Object.keys(schedule).forEach(function (name) {
Здесь может подойти `reduce`

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +        schedule[name].forEach(function (obj) {
А здесь `map`

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +    var timeIntervals = parseShedule(schedule).map(function (interval) {
Как считаешь, может стоит унести `map и toBankTimezone ` в `parseShedule`, 
чтобы не бегать два раза  – `parseShedule(schedule, bankTimezone)`?

Внутри `parseShedule` можно не упоминать `bankTimezone`,
а использовать более абстрактное – `baseTimezone`

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +    ]);
Почему не в один `concat`?

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +    ]);
Можно сделать chain от map: `.map().concat()`

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +            return true;
Можно `return Boolean(lastMoment)`

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +            var minutes = ('0' + new Date(lastMoment).getMinutes()).slice(-2);
👍, но я бы вынес в функцию

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +            var textDay = Object.keys(WEEK_DAYS).filter(function (weekDay) {
Можно `WEEK_DAYS` сделать массивом и работать с `indexOf`

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +                .replace(/(%DD)/, textDay)
Зачем здесь регулярное выражение?

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +            foundMoments.splice(0, 1);
Ломать коллекцию не самая дешёвая идея, лучше передвигать курсор

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +function toBankTimezone(interval, bankTimezone) {
Можно сделать функцию чуть универсальнее, исключив слово `bank`

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +function isCommonDay(firstDate, secondDate) {
Имелось в виду один и тот же день?  Тогда лучше подойдёт `isSameDay`

Или одна и та же дата? Тогда `isSameDate`

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +function getDurationInterval(endInterval, duration) {
endInterval -> from, так как функции лучше поменьше знать о контексте снаружи

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +        var durationInterval = getDurationInterval(firstInterval.to, duration);
Это скорее «мистер интервал-кандидат», чем «мистер интервал-продолжительность»

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +function isLessThan(duration, secondInterval) {
`duration` ты используешь как число везде, а здесь как интервал – затрудняет чтение кода

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +function isLessThan(duration, secondInterval) {
duration -> firstInerval

2016-11-03 05:52 UTC, gogoleff commented on robbery.js
> +function intersectionTimeIntervals(intervals) {
Можешь пояснить, что делает функция?

2016-11-03 05:52 UTC, gogoleff commented
🍅

2016-11-03 12:35 UTC, MozalovPavel commented on robbery.js
> +function intersectionTimeIntervals(intervals) {
Пересекает интервалы.

2016-11-03 16:10 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-11-03 16:10 UTC, honest-hrundel commented
@gogoleff обрати внимание решено доп. задание

2016-11-03 16:10 UTC, MozalovPavel commented
:green_apple:

2016-11-04 11:10 UTC, gogoleff commented on robbery.js
> +function intersectionTimeIntervals(intervals) {
Если опустить деталь `isInLimit`, то функция работает так:
```js
intersectionTimeIntervals([{from: 1, to: 4}, {from: 6, to: 8}])
// {from: 1, to: 4}, {from: 6, to: 8}

intersectionTimeIntervals([{from: 1, to: 4}, {from: 3, to: 8}])
// {from: 1, to: 4}, {from: 3, to: 8}

intersectionTimeIntervals([{from: 1, to: 4}, {from: 2, to: 3}])
// {from: 1, to: 4}
```

Не похоже не пересечение... Вопрос остаётся открытым

2016-11-04 11:10 UTC, gogoleff commented
🍅

2016-11-04 15:20 UTC, MozalovPavel commented on robbery.js
> +function intersectionTimeIntervals(intervals) {
Не правильно назвал. Он из не пересекает, а объединяет.

2016-11-04 15:20 UTC, MozalovPavel commented on robbery.js
> +function intersectionTimeIntervals(intervals) {
Если они пересекаются.

2016-11-04 15:24 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-11-04 15:25 UTC, honest-hrundel commented
@gogoleff обрати внимание решено доп. задание

2016-11-04 15:25 UTC, MozalovPavel commented
:green_apple:

2016-11-04 16:00 UTC, gogoleff commented
@MozalovPavel Вот теперь другое дело

2016-11-04 16:00 UTC, closed without merging

2016-11-04 16:01 UTC, gogoleff commented
@MozalovPavel Так как я сам задержал проверку – **полный балл**