Загнойко Александр
urfu-2016/javascript-task-3 pull request #3
Opened 2016-10-20 21:21 UTC by FoKycHuK

2016-10-20 21:21 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-20 21:32 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-20 21:32 UTC, honest-hrundel commented
@undefined обрати внимание решено доп. задание

2016-10-21 04:34 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-21 04:34 UTC, honest-hrundel commented
@undefined обрати внимание решено доп. задание

2016-10-21 04:52 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-21 04:52 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание решено доп. задание

2016-10-22 04:56 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-22 04:56 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание решено доп. задание

2016-10-23 10:18 UTC, Savichev-Igor commented on robbery.js
> +    var busyList = unionSchedule(schedule)
👍

2016-10-23 10:18 UTC, Savichev-Igor commented on robbery.js
> +        .map(parseTimeInterval)
👍

2016-10-23 10:54 UTC, Savichev-Igor commented on robbery.js
> +            });
Переносил бы закрывающую скобочку на уровень с` result.push` для читаемости

2016-10-23 10:55 UTC, Savichev-Igor commented on robbery.js
> +        result.push(
Ты можешь сделать это за один `push`

```
 result.push(
            {
                from: createDate(i, -bankTimeZone, 0),
                to: addToDate(bankTimeInterval.from, i, 0, 0)
            },
            {
                from: addToDate(bankTimeInterval.to, i, 0, 0),
                to: createDate(i + 1, -bankTimeZone, 0)
            }
);
```

2016-10-23 10:57 UTC, Savichev-Igor commented on robbery.js
> +        return Math.sign(firstInterval.from - secondInterval.from);
👍

2016-10-23 11:12 UTC, Savichev-Igor commented on robbery.js
> +        .replace('%HH', hours)
Когда-нибудь здесь можно будет использовать интерполяцию строк, а пока я закрываю это место рукой, чтобы не было так больно)

2016-10-23 11:12 UTC, Savichev-Igor commented on robbery.js
> +    // а day + 1 это потому, что нулевой день -- на самом деле день предыдущего месяца.
Использовал бы уж многострочный комментарий тогда)

2016-10-23 11:15 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-23 11:15 UTC, honest-hrundel commented
@Savichev-Igor обрати внимание решено доп. задание

2016-10-23 11:16 UTC, Savichev-Igor commented
🚀

2016-10-25 14:24 UTC, steppefox requested changes
🍅

2016-10-25 14:24 UTC, steppefox commented on robbery.js
> +    var groups = /([А-Я]*)\s*(\d\d):(\d\d)\+(\d+)/.exec(string);
Тут лучше вместо `\d\d` писать `\d{2}`, потому что так на совсем чуть-чуть лучше)

2016-10-25 14:24 UTC, steppefox commented on robbery.js
> +    var day = groups[1] ? BANK_WORKING_DAYS.indexOf(groups[1]) : 0;
Вот тут закрадывается небольшая ошибка. Давай представим, что у Линуса очень тяжелая неделя и он занят почти полностью:
```
Linus: [
  { from: 'ПН 09:00+5', to: 'ВТ 23:59+5' },
  { from: 'СР 08:30+5', to: 'ЧТ 15:00+5' } // Нужно очень много писать на PHP сутки на пролет
]
```

Для интервала `to` у тебя выдаст `day` равным -1, что потом превратится в прошедшее воскресенье и в итоге у Линуса будет не правильный интервал который позволит ограбить банк в Среду в 10 утра =(

2016-10-25 14:24 UTC, steppefox commented on robbery.js
> +    Object.keys(schedule).forEach(function (personSchedule) {
Здесь можно использовать `reduce`

2016-10-25 14:24 UTC, steppefox commented on robbery.js
> +    for (var i = 0; i < BANK_WORKING_DAYS.length; i++) {
Не слишком принципиально, но здесь тоже можно использовать `reduce`

2016-10-25 14:24 UTC, steppefox commented on robbery.js
> +        return Math.sign(firstInterval.from - secondInterval.from);
Мелочь конечно, но `Math.sign` в ES5 не было ;D Можешь не править)

2016-10-25 14:24 UTC, steppefox commented on robbery.js
> +    for (var i in busyList) {
у тебя где-то массивы перебираются 

`for (var i = 0; i < someList.length; i++) `, 

а где-то 

`for (var i in someList)`

Ты уж реши как нравится больше) Ну и к тому же, есть мнение что `var i in someList` не слишком быстр и весел)

2016-10-25 19:40 UTC, honest-hrundel commented
:warning: Вы не были зарегистрированы на курс.<br>Попробуйте написать организаторам (voirina@yandex-team.ru).<br>Или приходите к нам учиться осенью 2017 года.

2016-10-25 20:27 UTC, FoKycHuK commented
:green_apple:

2016-10-26 04:42 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-26 04:42 UTC, honest-hrundel commented
@steppefox обрати внимание решено доп. задание

2016-10-26 08:18 UTC, FoKycHuK commented
:green-apple:

2016-10-26 08:20 UTC, FoKycHuK commented
:green_apple:

2016-10-26 16:54 UTC, steppefox approved these changes
@FoKycHuK Отлично! В целом, мне все нравится. Отмечу что после первого прочтения, код сразу же был понятен и функции разбиты довольно чисто. Так держать! Удачи в следующих заданиях!

2016-10-26 16:55 UTC, closed without merging