Седова Ирина
urfu-2016/javascript-task-3 pull request #31
Opened 2016-10-24 12:33 UTC by IrinaSed

2016-10-24 12:33 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 19

2016-10-24 14:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-24 15:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 19

2016-10-24 17:21 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 19

2016-10-25 14:13 UTC, honest-hrundel commented
:tomato: Пройдено тестов 8 из 19

2016-10-25 21:46 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 19

2016-10-25 21:51 UTC, honest-hrundel commented
:tomato: Пройдено тестов 13 из 16

2016-10-25 22:02 UTC, honest-hrundel commented
:tomato: Пройдено тестов 17 из 19

2016-10-25 22:17 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-25 22:24 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-26 04:55 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-26 04:55 UTC, honest-hrundel commented
@bazhenova обрати внимание решено доп. задание

2016-10-27 17:27 UTC, bazhenova commented on robbery.js
> +var DAY = { 'ПН': 1, 'ВТ': 2, 'СР': 3, 'ЧТ': 4, 'ПТ': 5, 'СБ': 6, 'ВС': 7 };
Вообще непонятное название, у тебя тут точно не просто 1 day, но и все дни недели, надо переименовать

2016-10-27 17:29 UTC, bazhenova commented on robbery.js
> +var DAYWEEK = ['ПН', 'ВТ', 'СР'];
Во-первых, у тебя это дни недели, то есть как минимум имя переменной должно быть во множественном числе; во-вторых, по названию нельзя понять, что это только 3 дня из всей недели. Переименуй

2016-10-27 17:30 UTC, bazhenova commented on robbery.js
> +    // console.info(schedule, duration, workingHours);
Такие комментарии в коде не надо оставлять

2016-10-27 17:32 UTC, bazhenova commented on robbery.js
> +        timeZone: parseInt(workingHours.from.split('+')[1]),
У `parseInt` по-хорошему нужно указывать вторым аргументом систему счисления, чтобы избежать ошибок

2016-10-27 17:32 UTC, bazhenova commented on robbery.js
> +
Зачем тут добавлена пустая строка?

2016-10-27 17:33 UTC, bazhenova commented on robbery.js
> +                var ind = this.countTime;
По названию непонятно, что это за переменная

2016-10-27 17:34 UTC, bazhenova commented on robbery.js
> +        countTime: 0,
Что означает данное поле? Лучше бы его переименовать так, чтобы оно отражало свою суть

2016-10-27 17:34 UTC, bazhenova commented on robbery.js
> +                var timeARobbery = new Date(this.moments[ind].from + this.timeZone * 60 * 60000);
Вынеси в константу `60 * 60000`

2016-10-27 17:35 UTC, bazhenova commented on robbery.js
> +                var timeARobbery = new Date(this.moments[ind].from + this.timeZone * 60 * 60000);
Давай лучше назовем данную переменную `robberyTime`

2016-10-27 17:37 UTC, bazhenova commented on robbery.js
> +                return template.replace('%HH', pad(timeARobbery.getUTCHours()))
Когда у тебя идет несколько вызовов функций подряд, лучше каждый вызов начинать с новой строки. Перенеси данный `replace` на новую строку. Код станет красивее)

2016-10-27 17:38 UTC, bazhenova commented on robbery.js
> +            var timeARobbery = (duration + 30) * 60 * 1000;
`60 * 1000` -> константа

2016-10-27 17:38 UTC, bazhenova commented on robbery.js
> +                var newFrom = this.moments[ind].from + 30 * 60000;
`30 * 60000` -> константа

2016-10-27 17:40 UTC, bazhenova commented on robbery.js
> +                var ind = this.countTime;
Также посмотри в других местах в коде, это не единственное место, где ты используешь `ind`

2016-10-27 17:43 UTC, bazhenova commented on robbery.js
> +                var curr = this.moments[this.countTime].from;
лучше не сокращать названия переменных; во-первых, такие названия непонятны, во-вторых, в данной переменной `curr` (как я поняла, current) не отражен ее смысл. Текущее что?

2016-10-27 17:44 UTC, bazhenova commented on robbery.js
> +                var prev = this.moments[this.countTime - 1].from;
`prev` аналогично замечанию выше

2016-10-27 17:44 UTC, bazhenova commented on robbery.js
> +                if (curr - prev >= 30 * 6000) {
`30 * 6000` -> константа

2016-10-27 17:47 UTC, bazhenova commented on robbery.js
> +function pad(num) {
Для именования функций используй глаголы
Почитай еще разок https://github.com/urfu-2016/guides/blob/master/codestyle/js.md#Называйте-переменные-понятно

2016-10-27 17:49 UTC, bazhenova commented on robbery.js
> +    num = num < 10 ? '0' + num : num.toString();
Можно записать проще

``` js
return (num < 10 ? '0' + '') + num;
```

2016-10-27 17:53 UTC, bazhenova commented on robbery.js
> +    var busy = [];
Непонятное название. Занятой кто?  + это у тебя массив, подумай наз подходящим названием

2016-10-27 17:54 UTC, bazhenova commented on robbery.js
> +    addBusy(busy, schedule.Linus);
Вот этот кусок кода лучше переписать. Смотри, сейчас тебе известно, что у тебя 3 человека + ты знаешь их имена. А вдруг появится еще 1 человек, тогда мало того, что тебе надо будет знать его имя, но и придется дописать еще одну строчку кода. Есть принцип DRY, почитай о нем

2016-10-27 17:55 UTC, bazhenova commented on robbery.js
> +function busyBank(workingHours) {
в названии - глагол

2016-10-27 17:56 UTC, bazhenova commented on robbery.js
> +    return busy.sort(function (a, b) {
можно так:
```js
return busy.sort(function (a, b) {
    return a.from - b.from;
}
```

2016-10-27 17:58 UTC, bazhenova commented on robbery.js
> +function findBusyforDay(busy) {
название надо переименовать, непонятно, что за `busy` мы ищем

2016-10-27 17:58 UTC, bazhenova commented on robbery.js
> +    var newBusy = [];
что за `newBusy`? В названия надо вкладывать больше смысла

2016-10-27 18:00 UTC, bazhenova commented on robbery.js
> +        busy.forEach(function (item) {
`itemDay` и `item` не отражают смысл, переименуй

2016-10-27 18:01 UTC, bazhenova commented on robbery.js
> +    timetable.forEach(function (item) {
Используй `camelCase`
https://github.com/urfu-2016/guides/blob/master/codestyle/js.md#Называйте-переменные-понятно

2016-10-27 18:01 UTC, bazhenova commented on robbery.js
> +    timetable.forEach(function (item) {
переименуй `item`

2016-10-27 18:03 UTC, bazhenova commented on robbery.js
> +function parseDate(note) {
Что ты имеешь в виду под `note`?

2016-10-27 18:05 UTC, bazhenova commented on robbery.js
> +function disjointBusy(busy) {
Пишу сразу ко всей функции: надо переименовать название + все переменные тут. Вообще неочевидно

2016-10-27 18:06 UTC, bazhenova commented on robbery.js
> +function findBusyInterval(schedule, workingHours) {
Раз ты возвращаешь массив, то в названии это должно быть отражено, то есть тут лучше `findBusyIntervals`

2016-10-27 18:07 UTC, bazhenova commented on robbery.js
> +function findMoments(busyInterval, duration) {
`busyInterval` это массив -> `busyIntervals`

2016-10-27 18:07 UTC, bazhenova commented on robbery.js
> +        if (busyInterval[i + 1].from - busyInterval[i].to >= duration * 60000) {
`60000` -> константа

2016-10-27 18:07 UTC, bazhenova commented
🍅

2016-10-28 14:33 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-28 14:33 UTC, honest-hrundel commented
@bazhenova обрати внимание решено доп. задание

2016-10-28 17:50 UTC, bazhenova commented on robbery.js
> +var ROBBERY_TIME = ['ПН', 'ВТ', 'СР'];
это массив, поэтому `ROBBERY_TIMES`

2016-10-28 17:51 UTC, bazhenova commented on robbery.js
> +var DAY_BY_IND = { 'ПН': 1, 'ВТ': 2, 'СР': 3, 'ЧТ': 4, 'ПТ': 5, 'СБ': 6, 'ВС': 7 };
непонятное название, переименуй

2016-10-28 17:52 UTC, bazhenova commented on robbery.js
> +        currentId: 0,
текущий id чего?

2016-10-28 17:56 UTC, bazhenova commented on robbery.js
> +            if (this.exists()) {
В таких случаях лучше писать немного по-другому. Чтобы избежать большой вложенности, можно 'инвертировать' if, т.е.
```js
if (!this.exists()) {
    return '';
}
// тут остальная часть кода
```
Код становится и красивее и понятнее

2016-10-28 17:58 UTC, bazhenova commented on robbery.js
> +            var currentId = this.currentId;
вот тут бы тоже переименовать `currentId`, чтобы было понятно, что за текущий id

2016-10-28 18:00 UTC, bazhenova commented on robbery.js
> +                var offsetFrom = this.moments[this.currentId].from + OFFSET_TIME * MS_IN_MINUTES;
что означает данная переменная?

2016-10-28 18:01 UTC, bazhenova commented on robbery.js
> +function findBusyTime(schedule, workingHours) {
так как ты возвращаешь массив, то и в названии это должно быть отражено. Почему бы не назвать `findBusyIntervals`?

2016-10-28 18:02 UTC, bazhenova commented on robbery.js
> +    var intervalsBusy = [];
лучше назови `busyIntervals`

2016-10-28 18:02 UTC, bazhenova commented on robbery.js
> +    var intervalsBusyForBank = [];
и тут тоже лучше `busyIntervalsForBank`

2016-10-28 18:06 UTC, bazhenova commented on robbery.js
> +    ROBBERY_TIME.forEach(function (dayRobbery) {
смотри, как у тебя получается: ты бежишь по массиву с временем, и при этом элементом этого массива является день. Лучше переименуй либо `ROBBERY_TIME` в `ROBBERY_DAYS` и `dayRobbery` в `robberyDay`, либо `dayRobbery` в `robberyTime`

2016-10-28 18:06 UTC, bazhenova commented on robbery.js
> +function addBusyIntervals(intervalsBusy, timeTable) {
`intervalsBusy` -> `busyIntervals`

2016-10-28 18:07 UTC, bazhenova commented on robbery.js
> +
кажется, тут одна лишняя строчка)

2016-10-28 18:09 UTC, bazhenova commented on robbery.js
> +    var idGap = 0;
неочевидное название, сходу не сказать, что переменная в себе содержит. Надо именовать так, чтобы через год можно было открыть код и не вспоминать, а что же имелось в виду

2016-10-28 18:10 UTC, bazhenova commented on robbery.js
> +    var intervalslsBusy = findBusyTime(schedule, workingHours);
Ой, тут что-то названию поплохело. Раз у тебя функция называется `findBusyTime`, то и переменную неплохо бы назвать `busyTime`

2016-10-28 18:11 UTC, bazhenova commented
🍅

2016-10-28 18:38 UTC, IrinaSed commented on robbery.js
> +                var offsetFrom = this.moments[this.currentId].from + OFFSET_TIME * MS_IN_MINUTES;
offsetFrom?

2016-10-28 18:38 UTC, IrinaSed commented on robbery.js
> +                var offsetFrom = this.moments[this.currentId].from + OFFSET_TIME * MS_IN_MINUTES;
Какая?  offsetFrom?

2016-10-29 05:33 UTC, bazhenova commented on robbery.js
> +                var offsetFrom = this.moments[this.currentId].from + OFFSET_TIME * MS_IN_MINUTES;
да, `offsetFrom`, непонятно по названию, что это

2016-10-29 12:09 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-29 12:09 UTC, honest-hrundel commented
@bazhenova обрати внимание решено доп. задание

2016-10-29 14:38 UTC, bazhenova commented on robbery.js
> +        moments: findMoments(findBusyTimes(schedule, workingHours), duration),
По-хорошему бы лучше разбить эту строчку, а то получается, что у тебя вызывается функция, внутри которой вызывается еще одна функция. Например, если у тебя куча параметров в функции, которые тебе надо передать, но при этом их сначала надо получить, вызвав другие функции, то получать их внутри верхней функции - это плохая практика. Код становится менее читабельным. Т.е. тебе сначала надо получить данные, а потом передать их в функцию. Код станет и красивее и читабельнее. В данном случае, до `return` можно получить данные:
```js
var busyTimes = findBusyTimes(schedule, workingHours);
```
а потом в самом `return` передать эти данные:
```js
moments: findMoments(busyTimes, duration),
```

2016-10-29 14:38 UTC, bazhenova commented on robbery.js
> +            var dayRobbery = ROBBERY_DAYS[robberyTime.getUTCDay() - 1];
`dayRobbery` -> `robberyDay`

2016-10-29 14:45 UTC, bazhenova commented on robbery.js
> +            intervalsBusy.push({ from: robberyDay + ' ' + timeBusy.from,
На будущее по оформлению кода: поля в объектах нужно указывать либо все в одну строчку, либо каждое поле с новой строки. В данном случае можно было бы написать так:
```js
intervalsBusy.push({
    from: robberyDay + ' ' + timeBusy.from,
    to: robberyDay + ' ' + timeBusy.to
});
```

2016-10-29 14:49 UTC, bazhenova commented
Есть еще пара комментариев, но они как советы на будущее. Код стал намного читабельнее)

2016-10-29 14:50 UTC, bazhenova commented
🚀

2016-10-31 08:21 UTC, hrundik commented
У вас получилось два вида структур про время: с распарсенной датой, и с датой в виде строки. Распарсенную структуру стоит всегда создавать с помощью отдельной функции-фабрики, и добавить в структуру дополнительную полезную информацию: длительность, временную зону.

2016-10-31 08:22 UTC, hrundik requested changes
🍅

2016-10-31 08:22 UTC, hrundik commented on robbery.js
> +        idMoment: 0,
Можно вынести `idMoment` в замыкание функции (`var idMoment = 0;` перед `return`), чтобы доступ к ней был только из твоего кода.

2016-10-31 08:22 UTC, hrundik commented on robbery.js
> +        timeZone: parseInt(workingHours.from.split('+')[1], 10),
То же самое для `moments` и `timeZone`

2016-10-31 08:22 UTC, hrundik commented on robbery.js
> +                this.moments[idMoment] = { from: offsetMoment, to: this.moments[idMoment].to };
`this.moments[idMoment]` лучше вынести в переменную: `var moment = moments[idMoment]`

2016-10-31 08:22 UTC, hrundik commented on robbery.js
> +            if (this.moments[idMoment].to - this.moments[idMoment].from >= robberyTime) {
В объект интервала удобно добавить геттер `duration`. Тогда тут будет `if (moment.duration >= robberyTime)`

2016-10-31 08:22 UTC, hrundik commented on robbery.js
> +    var timeZone = workingHours.from.split('+')[1];
Код парсинга `timeZone` стоит вынести в отдельную функцию, поскольку используется он больше одного раза.

2016-10-31 08:22 UTC, hrundik commented on robbery.js
> +function joinIntervals(intervals) {
Наверное, правильнее эту функцию назвать `intersectIntervals`

2016-10-31 17:25 UTC, IrinaSed commented on robbery.js
> +                this.moments[idMoment] = { from: offsetMoment, to: this.moments[idMoment].to };
У меня перезаписываются элементы в moments по idMoment, и idMoment постоянно меняется, если я так сделаю, то мне придётся дублировать код. Что делать?

2016-10-31 17:27 UTC, IrinaSed commented on robbery.js
> +            if (this.moments[idMoment].to - this.moments[idMoment].from >= robberyTime) {
Из-за того что я выношу moments в замыкание и не могу сделать moment(комментарии ниже), то я не совсем понимаю как это сделать?

2016-10-31 17:35 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-31 17:35 UTC, honest-hrundel commented
@hrundik обрати внимание решено доп. задание

2016-10-31 21:00 UTC, hrundik requested changes
🍅

2016-10-31 21:00 UTC, hrundik commented on robbery.js
> +    var jointIntervals = [intervals[0]];
`intersectedIntervals`

2016-10-31 21:00 UTC, hrundik commented on robbery.js
> +            }
```javascript
var OFFSET_IN_MS = OFFSET_TIME * MS_IN_MINUTES;
// вынос в отдельную переменную делает код чуть компактнее, и помогает при чтении лучше понимать, 
// что в нём происходит. А код надо писать в первую очередь для читатетеля, а не для интерпретатора.
var moment = moments[idMoment];
if (moment.duration >= robberyTime) {
    // можно добавить метод .offset() к `moment`.
    // Таким образом вы переходите от прямой манипулции объектом передачи данных {from:, to: }
    // к инкапсуляции логики работы с "Моментом" в вашей терминологии 
    // В таком виде должно появляться желание ещё какие-то операции над "Моментами" унести поближе к самим моментам, от этого более сложную логику станет легче читать. Например, `moment.intersect(otherMoment)` сделает логику в `intersectIntervals` проще.
    moments[idMoment] = moment.offset(OFFSET_IN_MS);
    return true;
}
while (idMoment < moments.length - 1) {
    idMoment++;
// в этом месте не настаиваю, но в таком виде явно видно, что тут вы остаётесь в рамках всё тех же распарсенных интервалов/"моментов"
    var gapMoment = createMoment(moments[idMoment - 1].from, moments[idMoment].from); 
    if (gapMoment.duration >= OFFSET_IN_MS) {
         return true;
    }   
}
```

2016-11-01 12:00 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-11-01 12:00 UTC, honest-hrundel commented
@hrundik обрати внимание решено доп. задание

2016-11-01 12:28 UTC, hrundik approved these changes
👍

2016-11-01 12:28 UTC, hrundik commented on robbery.js
> +                });
👍 Так даже лучше, так выглядят `named parameters` в JS

2016-11-01 12:29 UTC, closed without merging