Кощеев Никита
urfu-2016/javascript-task-3 pull request #32
Opened 2016-10-24 13:58 UTC by ArchStanton9

2016-10-24 13:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-24 14:06 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-24 15:13 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 19

2016-10-24 18:06 UTC, honest-hrundel commented
:tomato: Пройдено тестов 4 из 19

2016-10-24 21:37 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-25 12:40 UTC, ArchStanton9 commented
Отсылал коммит, чтобы продолжить с другого ПК. Можно пока не проверять. Буду рефакторить.

2016-10-25 13:02 UTC, Savichev-Igor commented
@ArchStanton9 ок, жду

2016-10-25 19:23 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-25 19:30 UTC, ArchStanton9 commented
Ready for Review

2016-10-27 17:58 UTC, savichev-igor commented on robbery.js
> +        var time = date.match(/\d\d:\d\d:\d\d/)[0];
А почему выше использовал `{3}`, а тут `{2}` решил не использовать ?

2016-10-27 17:59 UTC, Savichev-Igor commented on robbery.js
> +            hours: time.match(/\d\d/g)[0],
И здесь

2016-10-27 17:59 UTC, Savichev-Igor commented on robbery.js
> +    var day = busyTime.match(/^[А-Я][А-Я]/)[0];
И здесь

2016-10-27 17:59 UTC, Savichev-Igor commented on robbery.js
> +    var hour = busyTime.match(/\d\d:\d\d/);
...

2016-10-27 18:00 UTC, Savichev-Igor commented on robbery.js
> +    function getTime(value) {
Ехал фанкшн через фанкшн, видит фанкшн фанкшн в фанкшн..

Ты уверен, что здесь нельзя произвести декомпозицию и не пихать функцию в функцию)?

2016-10-27 18:01 UTC, Savichev-Igor commented on robbery.js
> +    busyTime = '2016-10-' + day + 'T' + hour + ':00' + getUTC(busyTime).toString();
На мой вкус, лучше делать это так:
`busyTime = ['2016-10-', day, 'T', hour, ':00', getUTC(busyTime).toString()].join('');`

2016-10-27 18:02 UTC, savichev-igor commented on robbery.js
> +    var dayStart = 'ПН 00:00+' + bankUTC.value;
И тут аналогично

2016-10-27 18:03 UTC, savichev-igor commented on robbery.js
> +        var open = day + ' ' + workingHours.from;
И тут)

2016-10-27 18:06 UTC, savichev-igor commented on robbery.js
> +        if (a.value < b.value) {
Хоть это и не было в ES5, но посмотри в сторону `Math.sign`

2016-10-27 18:07 UTC, Savichev-Igor commented on robbery.js
> +                points.push(robberyTimePoints[i]);
Это можно сделать за один `push`

2016-10-27 18:07 UTC, Savichev-Igor commented on robbery.js
> +                points.push(robberyTimePoints[i + 1]);
Это можно сделать за один `push`

2016-10-27 18:07 UTC, Savichev-Igor commented on robbery.js
> +    function selectByDuration() {
Фанкшн через фанкшн

2016-10-27 18:08 UTC, savichev-igor commented on robbery.js
> +    duration = duration * 60 * 1000;
`60 * 1000` можно вынести в константу

2016-10-27 18:08 UTC, Savichev-Igor commented on robbery.js
> +                var dayRE = RegExp('(%[D][D])');
А зачем регвыры было выносить в переменные, ведь ты их 1 раз используешь ?

2016-10-27 18:09 UTC, Savichev-Igor commented on robbery.js
> +    timePoints = timePoints.concat(getBankTimePoints(workingHours));
Мне кажется, что алгоритм можно упростить..

Представь, что банк тоже участвует в ограблении и его можно рассматривать как грабителя, а не выделять отдельную сущность

2016-10-27 18:10 UTC, Savichev-Igor commented
🍅

2016-10-27 18:10 UTC, ArchStanton9 commented on robbery.js
> +        var time = date.match(/\d\d:\d\d:\d\d/)[0];
'\d'.length = 1
'{2}'.length = 3
Экономил ресурсы =)

2016-10-27 18:53 UTC, ArchStanton9 commented on robbery.js
> +        if (a.value < b.value) {
Возможно по этому intellisense мне такого и не предлагал.

2016-10-27 19:42 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-27 19:47 UTC, ArchStanton9 commented on robbery.js
> +    timePoints = timePoints.concat(getBankTimePoints(workingHours));
Тут, по моему, момент на любителя. Изначально я так и делал, но в процессе мне это решение показалось не самым удачным с точки зрения семантики. 
Более того, если представлять рабочие часы банка как расписание бандита, то приходится работать с данными полученными на входе. Сейчас же, я работаю с собственными структурами данных, что позволяет сократить количество операций и как следствие объем кода.

2016-10-27 19:54 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-27 19:55 UTC, ArchStanton9 commented
🍏

2016-10-27 20:02 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-27 20:05 UTC, ArchStanton9 commented
Чутка поторопился и не заметил лишний вызов функции, перед тем как кидать яблоко.
Надеюсь, ничего не сломалось.

2016-10-28 18:56 UTC, Savichev-Igor commented on robbery.js
> +            return '+' + UTC + '00';
А тут не через `join` :<

2016-10-28 18:57 UTC, savichev-igor commented on robbery.js
> +        schedule[robber].forEach(function (busyTime) {
Уверен, что здесь не обойтись без вложенных `forEach` или не воспользоваться `map/reduce` ?

2016-10-28 18:58 UTC, Savichev-Igor commented on robbery.js
> +        if (point.type === 'to') {
Может на конструкцию `switch` это переписать, хоть и два `if`'а, но мне кажется, что будет немного привлекательнее..

2016-10-28 18:59 UTC, Savichev-Igor commented on robbery.js
>      console.info(schedule, duration, workingHours);
Отладочные принты нужно убирать

2016-10-28 19:00 UTC, Savichev-Igor commented
В остальном вроде неплохо, поправь это и передам эстафету

2016-10-28 19:00 UTC, Savichev-Igor commented
🍅

2016-10-28 22:55 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-28 23:23 UTC, ArchStanton9 commented
По поводу двойного foreach, пожалуй, я уверен, что без них не обойтись. Заменить, конечно, можно, но если использовать map/reduce, то добавляются операции конкатенации массивов, в то время как в моем случае я делаю только push. Что касается производительности, до конца я не уверен, но делая push мы работаем с одним массивом, а соединяя массивы мы плодим новые сущности(на сколько я понял, в JS array это immutable тип). А вот лаконичность и читаемость кода совершенно точно теряется в моей реализации))

Остальное поправил.

2016-10-28 23:23 UTC, ArchStanton9 commented
🍏

2016-10-29 04:48 UTC, Savichev-Igor commented
:rocket:

2016-10-31 06:06 UTC, VorontsovMaxim requested changes
🍅 
В алгоритме достаточно много различных преобразований между строкам, числами, датами во всех вариациях из-за чего код довольно сложно читать и понимать.

Может можно придумать какой-то более удобный формат хранения и работы с данными?

Можно посмотреть  например в сторону "количество минут отсчитывая от какого-то старта"

2016-10-31 06:06 UTC, VorontsovMaxim commented on robbery.js
> +    var UTC = time.match(/\d$/);
Такая проверка даст неверный результат например в таком случае: `'ПН 10:00+10'`

2016-10-31 06:06 UTC, VorontsovMaxim commented on robbery.js
> +    var value = parseInt(UTC);
1. Лучше не пользоваться неявным поведением вызова `.toString()` у массива, а передавать нужную строку явно. В более общем случае, если бы элементов в массиве было больше чем один, результат был бы не верен.
2. Настоятельно рекомендую всегда явно указывать систему счисления: `parseInt(string, 10)`, чтобы избежать случайных ошибок

2016-10-31 06:06 UTC, VorontsovMaxim commented on robbery.js
> +    var dayStart = ['ПН 00:00', bankUTC.value].join('+');
На мой взгляд очень много лишних манипуляций со строками:
1. Собирается строка
2. Передается в `getTimePoint`
3. В `getTimePoint` она парсится, из нее собирается новая
4. Новая строка передается в `Date.parse`, получаем количество миллисекнд
5. Его мы передаем в `getTime`, там превращаем сначала в строку, а затем парсим ее
6. В итоге получаем объект

2016-10-31 06:06 UTC, VorontsovMaxim commented on robbery.js
> +        return Math.sign(a.value - b.value);
Достаточно просто `a.value - b.value`

2016-10-31 06:06 UTC, VorontsovMaxim commented on robbery.js
> +            return true;
Всю функцию выше можно записать проще: `Boolean(robberyTimePoints.length)`

2016-10-31 06:06 UTC, VorontsovMaxim commented on robbery.js
> +            if (robberyTimePoints.length !== 0) {
`Boolean(0) === false`
Поэтому в условии достаточно просто `robberyTimePoints.length`

2016-10-31 15:49 UTC, honest-hrundel commented
:tomato: Пройдено тестов 5 из 16

2016-10-31 16:02 UTC, honest-hrundel commented
:tomato: Пройдено тестов 14 из 16

2016-10-31 16:08 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 16

2016-10-31 16:20 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-31 16:31 UTC, ArchStanton9 commented
Поменял структуры данных.
Теперь объекты в массиве timePoints имеют только те поля, которые нужны в алгоритме обхода:
1) тип точки
2) действующее лицо
3) числовое значения в минутах, отсчитывая с начала недели

Время сейчас преобразую из строки в число при помощи getTimeValue(), а из числа в объект при помощи getTime(). Второе преобразование вызываю только при выводе результата, теперь уже не таская в объектах лишние данные.

Изначально сам себя ограничил тем, что хотел применить методы из лекции ( parseTime и replace), из-за чего потратил кучу времени и нервов.

Исправил метод сортировки и булевы выражения в экспортируемых функциях. Поправил парсинг часового пояса.

2016-10-31 16:31 UTC, ArchStanton9 commented
🍏

2016-11-01 17:16 UTC, VorontsovMaxim commented on robbery.js
> +        minute: minute > 9 ? minute.toString() : '0' + minute
Можно было вынести в функцию повторяющуюся логику по добавлению нолика

2016-11-01 17:17 UTC, VorontsovMaxim approved these changes

2016-11-01 17:17 UTC, VorontsovMaxim commented
Принято!

2016-11-01 17:17 UTC, closed without merging