Антонов Алексей
urfu-2016/javascript-task-3 pull request #37
Opened 2016-10-25 13:25 UTC by AlekseyAnt

2016-10-25 13:25 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-25 18:53 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-25 21:02 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-25 21:02 UTC, honest-hrundel commented
@Nikit0s обрати внимание решено доп. задание

2016-10-27 16:09 UTC, Nikit0s commented on robbery.js
> +var week = ['ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ', 'ВС'];
Можно в константы вынести

2016-10-27 16:10 UTC, Nikit0s commented on robbery.js
> +    return minutes * 60 * 1000;
60*1000 - тоже в константы

2016-10-27 16:10 UTC, Nikit0s commented on robbery.js
> +    var timeZoneOfBank = parseInt(workingHours.from.slice(5, 8), 10);
можно просто .slice(5)

2016-10-27 16:11 UTC, Nikit0s commented
В целом код понравился! 👍

2016-10-27 16:12 UTC, Nikit0s commented
🚀

2016-10-27 19:18 UTC, hrundik requested changes
🍅

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +    Object.defineProperties(obj, {
А зачем `Object.defineProperties`? Вы никакими особенностями этого АПИ не пользуетесь. Тут можно безболезненно использовать простой Object literal, код будет заметно легковеснее

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +                return intervals.length !== 0;
`intervals.length !== 0` стоит вынести в переменную и дать подходящее имя.

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +        return timeInterval.to - timeInterval.from >= workTime;
Уместно добавить метод `duration` в `timeInterval`, чтобы тут получилось `return timeInterval.duration() >= workTime`

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +    var timeZoneOfBank = parseInt(workingHours.from.slice(5, 8), 10);
Более того, у вас по коду два способа парсинга таймзон. Этот и выше, в методе `parseDate`. Должен быть один. Во `.from` вам приходит полноценная дата, лучше, чтобы здесь было что-то такое:

```
var timeZoneOfBank = parseDate(workingHours).timeZone; // метод `parseDate` вам не только тут поможет.
```

Для конвертации в `Number` допустимо использовать `+value` или `Number(value)` вместо `parseInt` (по условию у вас всегда валидные входные данные)

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +    var intervalsOfBankWork = parseTimeIntervals(timeIntervalsOfBankWork, timeZoneOfBank);
Можно унести вызов `parseTimeIntervals` внутрь `getNonFreeTimeIntervals` и `getTimeIntervalsOfBankWork`, чтобы не засорять логику.

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +function getNonFreeTimeIntervals(scheduleOfGangs) {
`NonFree` -> `Busy`

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +    return ((time < 10) ? '0' : '') + time.toString();
Явный вызов `.toString()` лишний, приведение к строке само произойдёт по правилам приведения.

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +function parseTimeIntervals(intervals, initialReferencePoint) {
`initialReferencePoint` -> `referenceTZ`, это ведь не точка, а таймзона.

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +    var date = dateStr.match(/([а-я]{2}) (\d{2}):(\d{2})/i);
Это не `date`, а результат парсинга даты. `Date` у вас ниже получится.

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +    var deffTimeZone = initialReferencePoint - currenttimeZone;
Что означает `deff`? Я не догадался. Не стоит сокращать.

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +    var currenttimeZone = parseInt(date.match(/\+(\d{1,2})/i)[0], 10);
`lowerCamelCase`: `currentTimeZone`.

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +    var newDate = rewriteDay(date);
Не вижу смысла выносить это в отдельный метод. Формат даты определён, даты без временной зоны у вас не будет. Тогда можно ограничиться одним регэкспом.

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +function parseDate(date, initialReferencePoint) {
`initialReferencePoint` -> `timeZone`. Это ведь просто временная зона, в которой вы хотите получить ответ.

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +                var start = new Date(suitableTimeIntervals[0].from);
А вы понимаете, почему эта строчка создаёт копию даты?

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +        if (interval.to <= timeIntervals[i].from) {
Текущий итерируемы элемент почти всегда уместно выносить в переменную:
`var currentInterval = timeIntervals[i]`
И в теле цикла работать уже с ним.

2016-10-27 19:18 UTC, hrundik commented on robbery.js
> +    }
Крайне сложная и неочевидная логика с множественными точками выхода и завершения итераций. Это почти как `goto`.  Попробуйте упростить, чтобы была только одна точка выхода из метода. Ещё вы тут в несовсем явном виде ищете пересечение двух интервалов, это стоит вынести в отдельную функцию.

2016-10-29 10:53 UTC, AlekseyAnt commented on robbery.js
> +                var start = new Date(suitableTimeIntervals[0].from);
В конструкторе Date аргумент .from приводится к числовому значению(default value). Затем это значение преобразуется методом Date.parse в новый объект типа Date. В итоге получается копия объекта.

2016-10-29 10:53 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2016-10-29 11:14 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-29 11:14 UTC, honest-hrundel commented
@hrundik обрати внимание решено доп. задание

2016-10-29 11:34 UTC, hrundik approved these changes

2016-10-29 11:35 UTC, hrundik commented
👍

2016-10-29 11:35 UTC, closed without merging