Кошара Павел
urfu-2016/javascript-task-3 pull request #4
Opened 2016-10-21 07:35 UTC by melanholy

2016-10-21 07:35 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 19

2016-10-21 08:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-21 08:32 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-21 08:32 UTC, honest-hrundel commented
@mironov-alexey обрати внимание решено доп. задание

2016-10-21 14:27 UTC, m1ralx reviewed
:tomato:

2016-10-21 14:27 UTC, m1ralx commented on robbery.js
> +    duration *= 60;
тут и в предыдущей строке изменяется то, что пришло в параметрах функции. Лучше так не делать и создавать новые переменные, названия которых будет лучше отображать то, что в них находится. Например, потом можно легко забыть, что в `schedule` уже лежит не просто `schedule`, а `normalizedSchedule`, аналогично с `duration`

2016-10-21 14:27 UTC, m1ralx commented on robbery.js
> +    var bankTimezone = parseInt(/\+(\d+)$/.exec(workingHours.from)[1]);
В `parseInt` нужно вторым аргументом указывать основание системы счисления. Чаще всего это, конечно `10`. Так исторически сложилось, что в некоторых средах, в которых исполняется js, дефолтное значение этой системы не 10, а 8. Т.е. например, `parseInt("0302");` вернёт `194`.

2016-10-21 14:27 UTC, m1ralx commented on robbery.js
> +    var weekStart = Date.parse('1 1 1970 00:00 GMT+' + bankTimezone) / 1000;
На первый взгляд не очень понятно, что это за magic-constant строки. В частности, почему именно 1970 год? :)

2016-10-21 14:27 UTC, m1ralx commented on robbery.js
> +    var robberyTime = [];
Может лучше `robberyTimes`? Это же список.

2016-10-21 14:27 UTC, m1ralx commented on robbery.js
> +    var spareTime = getSpareTimes(schedule, weekStart, deadline);
Тут кстати то же, что в комментарии ниже :) Функция называется `getSpareTimes` и по всей видимости возвращает список отрезков, а переменная в единственном числе названа.

2016-10-21 14:27 UTC, m1ralx commented on robbery.js
> +    workingDays.forEach(function (workingDay) {
Возможно, стоит спрятать этот код в ещё одну функцию с говорящим названием. Но в общем-то, это не критично и можно так оставить.

2016-10-21 14:27 UTC, m1ralx commented on robbery.js
> +                .toLocaleString(undefined, { 'minimumIntegerDigits': 2 });
воу-воу да это же DRY! :) Немного конечно, но можно прибрать

2016-10-21 14:27 UTC, m1ralx commented on robbery.js
> +            if (robberyTime[0].to - robberyTime[0].from - THIRTY_MINUTES >= duration) {
Константа это конечно хорошо и всё такое, но тебе не кажется, что она объявлена как-то далеко от места использования. Да и в других методах она не используется. Может быть лучше инициализировать её тут? Тогда тому, кто читает код не придётся искать её где-то

2016-10-21 14:27 UTC, m1ralx commented on robbery.js
> +            date.setTime((robberyTime[0].from + bankTimezone * 3600) * 1000);
Можно миллисекунды в конструктор `Date` передавать

2016-10-21 14:27 UTC, m1ralx commented on robbery.js
> +function getSpareTimes(schedule, weekStart, deadline) {
Вот тут, кстати, уже не совсем очевидно, что имеется в виду не то `schedule` которое на входе, а то, которое ты уже нормализовал

2016-10-21 14:27 UTC, mironov-alexey commented on robbery.js
> +        var from = DAYS[i] + ' ' + workingHours.from;
Я правильно понимаю, что все дни, у которых индекс `>= 3` нигде не используются? Может от них избавиться?

2016-10-21 14:27 UTC, mironov-alexey commented on robbery.js
> +        var from = DAYS[i] + ' ' + workingHours.from;
Тогда можно будет и тут до `DAYS.length` итерироваться и исчезнет константа 3 :)

2016-10-21 14:27 UTC, mironov-alexey commented on robbery.js
> +            'from': dateToTimestamp(from),
Можно, кстати, не писать `'from'` в кавычках. Без них тоже ок будет:
```javascript
{
   from: 123
}
```

2016-10-21 14:27 UTC, mironov-alexey commented on robbery.js
> +        spareTime.push({ 'from': current, 'to': schedule[i].from });
И тут можно без кавычек. А ещё ты где-то пишешь подобные объявления в одну строчку
```javascript
{ 'from': current, 'to': schedule[i].from }
```
а где-то в несколько

```javascript 
workingDays.push({
    'from': dateToTimestamp(from),
    'to': dateToTimestamp(to)
});
```
Вряд ли есть какой-то _правильный_ стиль, но лучше делать везде однообразно

2016-10-21 14:27 UTC, mironov-alexey commented on robbery.js
> +        if (one.from > another.from) {
Может быть `Math.sign` поможет?

2016-10-21 14:27 UTC, mironov-alexey commented on robbery.js
> +    busyIntervals = busyIntervals.sort(function (one, another) {
`sort` изменяет исходный массив (но и возвращает его, да) так что это присвоение бессмысленное по двум причинам :) Можно просто `return busyIntervals.sort...`

2016-10-21 14:27 UTC, mironov-alexey commented on robbery.js
> +    return Date.parse(str) / 1000;
Прост интересно, а зачем ты везде избавляешься от миллисекунд?

2016-10-21 14:39 UTC, melanholy commented on robbery.js
> +        var from = DAYS[i] + ' ' + workingHours.from;
"Все время задачи ограничено неделей c ПН 00:00 до ВС 23:59 в часовом поясе банка"
быть может в расписании членов команды фигурируют дни больше среды

2016-10-21 15:28 UTC, mironov-alexey commented on robbery.js
> +        var from = DAYS[i] + ' ' + workingHours.from;
Окей, спасибо 👍🏻

2016-10-21 15:34 UTC, melanholy commented on robbery.js
> +    var weekStart = Date.parse('1 1 1970 00:00 GMT+' + bankTimezone) / 1000;
как можно объяснить, что это число было выбрано путем 4 бросков девятистороннего кубика?

2016-10-21 16:24 UTC, mironov-alexey commented on robbery.js
> +    var weekStart = Date.parse('1 1 1970 00:00 GMT+' + bankTimezone) / 1000;
Юниксовый какой-то кубик, ну ок

2016-10-21 17:16 UTC, m1ralx reviewed
🚀

2016-10-21 17:16 UTC, m1ralx commented on robbery.js
> +    return DAYS.reduce(function (acc, day) {
👍  🔥

2016-10-21 17:16 UTC, m1ralx commented on robbery.js
> +                robberyIntervals.shift();
Я бы кстати написал так

``` javascript
return !!robberyIntervals.shift();
```

но ментор наверн будет ругаться. Так что лучше оставить так 😆

2016-10-22 05:21 UTC, mironov-alexey commented
:rocket:

2016-10-22 05:25 UTC, mironov-alexey commented
:rocket:

2016-10-22 09:29 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-23 19:26 UTC, Vittly commented on robbery.js
> +    var bankTimezone = parseInt(/\+(\d+)$/.exec(workingHours.from)[1], 10);
капец, как сложно:
- создали регвыр
- применили регвыр
- взяли капчер
- привели к числу через `parseInt`

все про регвыр лучше унести в хелпер - можно надежнее написать:

```js

function getTimezoneFrom(stamp) {
    var match = /\+(\d+)$/.exec(stamp);

    // match-а ведь может и не быть
    return match && Number(match[1]); // parseInt нужен, если мы уверены только в том, что строка начинается с цифр, а дальше могут быть буквы - тут стопудов у нас только цифры
}
```

2016-10-24 04:31 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-24 04:31 UTC, honest-hrundel commented
@Vittly обрати внимание решено доп. задание

2016-10-24 09:32 UTC, Vittly commented
:tomato:

2016-10-24 09:33 UTC, Vittly requested changes

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +    isoDate = isoDate.replace(/(\d) (\d{2}:\d{2})(\+\d+)?/, '1 $1 1970 $2 GMT$3');
GMT можно выкинуть

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +    });
можно еще так:

``` js
isoDate = date.replace(/ПН|ВТ|СР/, function (day) {
    return DAYS.indexOf(day) + 1;
});
```

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +    return Object.keys(schedule).reduce(function (acc, thug) {
`acc` -> `intervals` или `result`

`thug` -> `thugName`?

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +        acc = acc.concat(busy);
я бы так написал (не знаю, пустит ли линтер):

``` js
return acc.concat(
    schedule[thug].map(toTimestampInterval)
);
```

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +    isoDate = isoDate.replace(/(\d) (\d{2}:\d{2})(\+\d+)?/, '1 $1 1970 $2 GMT$3');
еще правильнее писать полный регесп - `^(\d) (\d{2}:\d{2})(\+\d+)?$` - типа добавить крышку и доллар. Кстати, а почему таймзоны может не быть? Ты в курсе, что тогда возьмется локальная?

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +    var deadline = dateToTimestamp('СР 23:59+' + bankTimezone);
пока просто мысли вслух: у тебя есть хеплер `getWorkingDays` - который уже внутри содержит знание о том, что на ограбление есть пн-ср (кстати, тогда название должно об этом говорить - м.б. `getAppropriateIntervals`) - поэтому `weekStart` и `deadline` уже не нужны

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +        return Math.sign(one.from - another.from);
можно без `Math.sign`

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +        current = current < interval.to ? interval.to : current;
Во-первых, это пишется так: `current = Math.max(...)`.

~~Во-вторых, почему так? Что мы пытаемся сделать в алгоритме? Если получить непересекающиеся интервалы, то не надо ли делать `current = Math.max(current, interval.from)`?~~ Въехал, мы тут находим "дырки" при вычитании из времени на ограбление и занятое время грабителей -  типа ищем их свободное время

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +            var maxFrom = Math.max(day.from, interval.from);
я бы назвал переменные иначе - так как `min` и `max` описывают способ их вычисления, а не их смысл. Мое предложение: `attemptFrom` и `attemptTo`

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +            if (!this.exists()) {
можно и так:

``` js
var robbery = robberyIntervals[0];

if (!robbery) {
    return '';
}

// ...
```

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +            var date = new Date(robberyIntervals[0].from + bankTimezone * hourInMilliseconds);
воу-воу, а ограбление разве не в часовом поясе банка уже? наверное тут, дабы утащить время в UTC0, надо делать `- bankTimezone * hourInMilliseconds`? Или я неправ?

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +    isoDate = isoDate.replace(/(\d) (\d{2}:\d{2})(\+\d+)?/, '1 $1 1970 $2 GMT$3');
Раз ниже используешь `getUTCMinutes` и `getUTCHours` - может тут будем тоже `UTC`, а не `GMT` писать - для однородности

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +}
:fire:

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +}
но ты его кроме как с двойкой не используешь, поэтому можно переименовать в `twoDigitsFormat(number)`

2016-10-24 09:33 UTC, Vittly commented on robbery.js
> +                }
нет, не согласен.

По первой части: ты пробуешь попробовать ограбить в тот же интервал с задержкой, но оставляешь сайдэффект, о котором никто в задаче не просит - правишь `robberyIntervals` - это лишнее - просто верни `true`.

По второй части: ты снова изменяешь `robberyIntervals` - зачем? Плюс, ты считаешь, что второй интервал обязательно подойдет - но почему? Откуда уверенность что `robberyIntervals[1].from - robberyIntervals[0].from > halfHourInMilliseconds`? Это надо проверять

2016-10-24 11:33 UTC, melanholy commented on robbery.js
> +                }
1. Следующий вызов format уже должен вернуть новое время. После вызова tryLater уже нет возможности вернуться на старое время. Да и как format без сайдэффектов потом узнает, что нужно вернуть не самое ранее время?

2.  robberyIntervals состоит исключительно из благоприятных для ограбления промежутков по построению. Про сайдэффекты то же самое

2016-10-24 11:37 UTC, melanholy commented on robbery.js
> +            var date = new Date(robberyIntervals[0].from + bankTimezone * hourInMilliseconds);
Тесты для выявления таких ошибок и нужны. Все интервалы в коде в UTC.

2016-10-24 11:39 UTC, melanholy commented on robbery.js
> +    });
Мне кажется, что Ваш вариант медленнее

2016-10-24 11:40 UTC, Vittly commented on robbery.js
> +                }
1. Спросил ребят, да, похоже, требование такое - сайдэффекты ок

2016-10-24 11:41 UTC, Vittly commented on robbery.js
> +                }
2. Это не ответ - `robberyIntervals[1].from - robberyIntervals[0].from > halfHourInMilliseconds` - это же не обязательно

2016-10-24 11:43 UTC, Vittly commented on robbery.js
> +                }
уточню - `duration` может быть меньше получаса, например - 5 минут. Тогда следующий период может быть после первого - через 10 минут, а не через 30

2016-10-24 11:46 UTC, melanholy commented on robbery.js
> +    var deadline = dateToTimestamp('СР 23:59+' + bankTimezone);
Это и padNumberLeft: да, в кодстайле сказано не писать лишние вещи. Но курс ООП научил нас такой штуке как "переиспользование кода". 
Мне кажется, что эти функции содержат не очень много лишнего функционала, а их направленность на кокретную задачу противоречит ООП.

2016-10-24 11:46 UTC, Vittly commented on robbery.js
> +    });
Ваш - твой, пожалуйста) Согласен, насколько медленнее? Из явных плюсов - в моем варианте семантика кода ближе к задаче - код написан ровно так как от него требуется

2016-10-24 11:47 UTC, Vittly commented on robbery.js
> +            var date = new Date(robberyIntervals[0].from + bankTimezone * hourInMilliseconds);
тогда прошу мне объяснить на примере, где я неправ в своих рассуждениях

2016-10-24 12:04 UTC, melanholy commented on robbery.js
> +    var deadline = dateToTimestamp('СР 23:59+' + bankTimezone);
Если бы я был грабителем, то я учел бы что следующий банк может не менять сигнализацию вообще, а проблема выбора подходящего времени все равно есть)

2016-10-24 12:09 UTC, Vittly commented on robbery.js
> +    var deadline = dateToTimestamp('СР 23:59+' + bankTimezone);
Все правильно говоришь, но тут есть несколько "но". Переиспользование должно быть востребовано.
Примеры:
1. Есть команда, которая делает сложную задачу. Задача обсуждается, выделяются этапы - подзадачи, работа распределяется. Таким образом, делая этап №1, команда не просто делает конкретные задачи, а делает их так, чтобы потом было удобно выполнить этапы №2,3 ... Тут как раз надо делать "чуть больше", чем нужно прямо сейчас, потому что мы понимаем, зачем мы это делаем.
2. Есть конкретная задача, понимание, что это не последняя задача по заданной теме. Какие задачи потом будут, я не знаю, но знаю что они будут. Тогда на основе опыта нужно "предугадать", как лучше писать - где делать узко, где немного шире.

В данном случае ни один из вариантов не подходит, поэтому я предлагаю упростить. Тем более мое упрощение не убьет напрочь твою задумку - ее легко будет вернуть простым рефакторингом

2016-10-24 12:10 UTC, Vittly commented on robbery.js
> +    var deadline = dateToTimestamp('СР 23:59+' + bankTimezone);
> Если бы я был грабителем, то я учел бы что следующий банк
принято)

2016-10-24 12:43 UTC, melanholy commented on robbery.js
> +                }
ах, с трудом понял. плохие тесты, видимо

2016-10-24 12:46 UTC, melanholy commented on robbery.js
> +            var date = new Date(robberyIntervals[0].from + bankTimezone * hourInMilliseconds);
Date.parse возвращает таймстамп, который по определению в UTC. Все интервалы состоят из этих таймстампов. Когда в дате пишется `10:00+5`, имеется в виду сдвиг на 5 часов вперед относительно UTC. Этот сдвиг я к имеющемуся таймстампу и добавляю, дабы получить дату в часовом поясе банка

2016-10-24 12:48 UTC, Vittly commented on robbery.js
> +                }
да, видимо тесты не покрывают

2016-10-24 12:51 UTC, Vittly commented on robbery.js
> +            var date = new Date(robberyIntervals[0].from + bankTimezone * hourInMilliseconds);
это я все понимаю) просто `robberyIntervals` уже посчитаны в зоне банка, то есть сдвиг уже зашит - а ты еще раз добавляешь, поэтому спрашиваю

2016-10-24 12:54 UTC, melanholy commented on robbery.js
> +            var date = new Date(robberyIntervals[0].from + bankTimezone * hourInMilliseconds);
вообще все интервалы у меня в UTC, включая robberyIntervals

2016-10-24 13:02 UTC, melanholy commented on robbery.js
> +    isoDate = isoDate.replace(/(\d) (\d{2}:\d{2})(\+\d+)?/, '1 $1 1970 $2 GMT$3');
Если UTC или GMT(которые судя по всему на практике идентичны) указаны, то местное время точно не возьмется, а возьмется UTC+0

2016-10-24 13:03 UTC, melanholy commented on robbery.js
> +    isoDate = isoDate.replace(/(\d) (\d{2}:\d{2})(\+\d+)?/, '1 $1 1970 $2 GMT$3');
собственно они и написаны чтобы не было проблем с машинами в разных временных зонах

2016-10-24 13:06 UTC, Vittly commented on robbery.js
> +    isoDate = isoDate.replace(/(\d) (\d{2}:\d{2})(\+\d+)?/, '1 $1 1970 $2 GMT$3');
> а возьмется UTC+0

нет, у меня на машине, например, не так

2016-10-24 13:09 UTC, melanholy commented on robbery.js
> +    });
из минусов - при добавлении нового дня придется и регулярку менять вместе с массивом дат
про скорость я пожалуй возьму свои слова назад, уже не так уверен

2016-10-24 13:14 UTC, Vittly commented on robbery.js
> +            var date = new Date(robberyIntervals[0].from + bankTimezone * hourInMilliseconds);
аааа, допер - типа внутри `robberyIntervals` уже есть сдвиг (за счет `isoDate.parse('... GMT$3')`) - но тут мы хотим получить "чистое время" - типа без сдвига, а тогда мы должны еще плюсануть сдвиг времени банка, как-то так:

`format = UTC((time + zone) + zone) // вызов UTC внешний zone отбросит`

2016-10-24 13:15 UTC, Vittly commented on robbery.js
> +    });
да, регвыр придется синхронизировать - убедил, тут больше не пристаю

2016-10-24 13:15 UTC, melanholy commented on robbery.js
> +    isoDate = isoDate.replace(/(\d) (\d{2}:\d{2})(\+\d+)?/, '1 $1 1970 $2 GMT$3');
```
> Date.parse('1 1 1970 1:00') 
-14400000 
> Date.parse('1 1 1970 1:00 UTC') 
3600000
```
то есть я неправ если утверждаю что второй вариант везде вернет 3600000? добавить +0 не выглядит решением и получается что задача взятия времени по Гривичу становится нерешаемой

2016-10-24 13:18 UTC, Vittly commented on robbery.js
> +    isoDate = isoDate.replace(/(\d) (\d{2}:\d{2})(\+\d+)?/, '1 $1 1970 $2 GMT$3');
ой, теперь понял, в чем проблема. Да, прав, что второй вариант хороший. Я тут предлагаю вместо `GMT` писать `UTC` (так как вроде одно и тоже и ниже ты используешь UTC-методы) и еще прошу объяснить мне, вот это:

> (\+\d+)?/

когда мы в задаче парсим время без зоны?

2016-10-24 13:25 UTC, melanholy commented on robbery.js
> +    isoDate = isoDate.replace(/(\d) (\d{2}:\d{2})(\+\d+)?/, '1 $1 1970 $2 GMT$3');
не очень внимательно читал задание

2016-10-24 15:40 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-24 15:40 UTC, honest-hrundel commented
@Vittly обрати внимание решено доп. задание

2016-10-24 15:44 UTC, melanholy commented
🍏

2016-10-24 16:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-24 16:59 UTC, honest-hrundel commented
@Vittly обрати внимание решено доп. задание

2016-10-25 09:21 UTC, Vittly commented on robbery.js
> +            }
Как-то сложно получилось, и, главное, кажется с логикой проблемы. Чего мы хотим? Нам нужно:
- либо интервал, который начинается позже `delayedRobberyStart`
- либо интервал, который начинается раньше, но его время, отсчитанное от `delayedRobberyStart` было больше `duration`

Мне кажется, не надо два кейса мешать в один. Лучше написать так:

```js
var i = 0;

// 1ый кейс
while (i < robberyIntervals.length && robberyIntervals[i].from < delayedRobberyStart) {
    if (robberyIntervals[i].to - delayedRobberyStart >= durationInMilliseconds) {
        robberyIntervals[i].from = delayedRobberyStart;
        robberyIntervals = robberyIntervals.slice(i);

        return true;
    }
    i++;
}

// 2ой кейс
if (i < robberyIntervals.length) {
    robberyIntervals = robberyIntervals.slice(i);
    return true;
}
```

Так что пока еще 🍅

2016-10-25 16:20 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-25 16:20 UTC, honest-hrundel commented
@Vittly обрати внимание решено доп. задание

2016-10-25 16:21 UTC, melanholy commented
🍏

2016-10-26 06:12 UTC, Vittly commented on robbery.js
> +            }
так, а чего мы slice не сделали? типа: `robberyIntervals  = robberyIntervals.slice(i)` ? Вон в строчке №181 мы же оставляем сайдэффект - правим границу интервала, но элементы остаются не местах. Как ты мне сам объяснял, должен работать следующий `tryLater` - как еще на полчаса дальше

2016-10-26 06:48 UTC, melanholy commented on robbery.js
> +            }
Теперь слайсы не нужны. Я решил хранить указатель на текущий самый ранний(с учетом попыток начать позже) интервал для ограбления

2016-10-26 07:41 UTC, Vittly commented on robbery.js
> +            }
мм, понял тебя. Только не понятно, как это согласуется с работой метода `exists` - он же тоже должен учитывать `currentRobberyIndex` - а то, например, сломается `format` (что наводит нас на мысль, что все таки стоит делать slice)

но это уже придирки, с задачей ты разобрался

2016-10-26 09:42 UTC, melanholy commented on robbery.js
> +            }
Тогда можно закрыть, наверное?)

2016-10-26 09:43 UTC, melanholy commented on robbery.js
> +            }
И ничего не сломается, т.к. currentRobberyIndex в exists не используется

2016-10-26 09:50 UTC, melanholy commented on robbery.js
> +            }
Точнее, robberyIndex не превысит длину robberyIntervals(если robberyIntervals не пуст)

2016-10-26 09:50 UTC, Vittly commented on robbery.js
> +            }
еще раз, сломается, я же написал

``` js

if (!this.exists()) { // не посмотрели на currentRobberyIndex, а он, может быть, уже больше длины
    return '';
}
var hourInMilliseconds = 60 * 60 * 1000;
var date = new Date(
    robberyIntervals[currentRobberyIndex].from + // бдыжь, бах, бум! все взорволось, undefined is not an object
```

~~не торопись так в выводах, читай внимательнее набросы, я же их пишу, чтоб чему-то научить~~

2016-10-26 09:52 UTC, Vittly commented on robbery.js
> +            }
> robberyIndex не превысит длину robberyIntervals
это другой разговор:)

2016-10-26 10:25 UTC, melanholy commented on robbery.js
> +            }
Что-то я запутался. Если currentRobberyIndex равен 0 и exists вернет true, то нулевой элемент в robberyIntervals есть. Если currentRobberyIndex больше 0, то смотрим где он меняется:
```
            while (i < robberyIntervals.length && robberyIntervals[i].from < delayedRobberyStart) {
                if (robberyIntervals[i].to - delayedRobberyStart >= durationInMilliseconds) {
                    robberyIntervals[i].from = delayedRobberyStart;
                    currentRobberyIndex = i;

                    return true;
                }
                i++;
            }

            if (i < robberyIntervals.length) {
                currentRobberyIndex = i;

                return true;
            }
```
В обоих случаях присвоение произойдет только тогда, когда присваимое значение(i) меньше длины robberyIntervals, то есть если exists вернет true, то robberyInterval[currentRobberyInterval] != undefined.

2016-10-26 10:30 UTC, Vittly commented on robbery.js
> +            }
дело в том, что комменты:

> Точнее, robberyIndex не превысит длину...

и

> еще раз, сломается, я же написал...

мы написали почти одновременно, и когда я писал свой - твоего еще не было. Я  не заметил, что `robberyIntervals` меняясь не убежит за длину. Потом я запостил свой коммент и тут же увидел твой и все понял. А в последнем комменте ты еще раз все проговорил, спасибо

2016-10-26 10:30 UTC, Vittly approved these changes

2016-10-26 10:31 UTC, Vittly commented
@melanholy, Молодец!

2016-10-26 10:31 UTC, closed without merging