IrinaShmonina
urfu-2016/javascript-task-3 pull request #58
Opened 2016-10-26 18:53 UTC by IrinaShmonina

2016-10-26 18:54 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 16

2016-10-26 18:56 UTC, honest-hrundel commented
:tomato: Пройдено тестов 9 из 16

2016-10-26 18:59 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 16

2016-10-26 19:03 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 16

2016-10-26 19:20 UTC, honest-hrundel commented
:tomato: Пройдено тестов 15 из 16

2016-10-26 19:59 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-27 13:05 UTC, m1ralx reviewed
bump

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +var DATE = /^([А-Я]{2})?[ ]?(\d\d)[:](\d\d)\+(\d+)$/;
хороший регвыр, ~~но где-то я его [уже видел](https://github.com/urfu-2016/javascript-task-3/pull/15/files#diff-81f6e4d51e4e6843d803fca2e3b73ceaR10)~~ но можно лучше

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +var shift = 0;
Что это за сдвиг и почему он рядом с константами?

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    var start = getMinut(timeFrom); // in minuts
`getMinutes`?

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +function getTime(timeFrom, timeTo) {
`getInterval` ?

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    shift = parseInt(rez[3]);
Глобальные переменные -- плохо. Подумай, как можно без этого

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    var rez = str.match(re);
Называй переменные так, чтобы было понятно, что в них находится.

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    var re = /^(\d\d):(\d\d)[+](\d)$/;
Можно сделать регэксп константой и не создавать его каждый раз в функции

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    return (parseInt(rez[1]) * HOUR + parseInt(rez[2]));
указывай основание системы счисления вторым параметром в `parseInt`

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +function getTimeForAll(schedule) {
`forAll` -- это что, что такое `All?`?

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    var rez = [];
ну в крайнем случае `result`

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    var rez = [];
хотя это тоже плохо. Можно назвать нормальным словом, которое будет отображать, что же там в этом массиве.

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    var listTime = schedule.Danny.concat(schedule.Rusty).concat(schedule.Linus);
а если бы грабителей было не 3 а 500, ты бы написала 499 раз `concat`?

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    var listTime = schedule.Danny.concat(schedule.Rusty).concat(schedule.Linus);
И если даже грабителей трое, но у них вдруг будут другие имена, тебе нужно будет каждое такое место в коде найти и поменять на нужные имена

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    var listTime = schedule.Danny.concat(schedule.Rusty).concat(schedule.Linus);
а ещё:
1) `list` в названии не нужно указывать
2) название должно соотноситься с тем, что лежит в переменной: если это какой-то список, то имя переменной должно быть в множественном числе.

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +function searchTimeInAllRang(timeBank, time, busyTime, day) {
В этой функции все те же проблемы, что и раньше.

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +    if (busyTime.every(function (bTime) {
Такие условия лучше выносить в отдельную переменную.

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +        if (startRobbery !== undefined) {
`return startRobbery`?
или даже лучше искать сразу все интервалы, если будешь делать звёздочку.

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +        startRobbery = searchTimeInAllRang(timeWorkBank, duration, freeTimeAllParticipants, i);
Пользуйся каким-нибудь онлайн-словарём или переводчиком, если не уверена, как правильно написать слово.

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +            var date = createDateFromMinures(startRobbery);
`Minutes`?

2016-10-27 13:05 UTC, m1ralx commented on robbery.js
> +            return template.replace(/%HH/, date.hours)
лучше выравнивать такие вызовы вот так

``` javascript
return template.replace(/%HH/, date.hours)
               .replace(/%MM/, date.minutes)
               .replace(/%DD/, date.day);
```

2016-10-27 13:05 UTC, mironov-alexey commented on robbery.js
> +function convertToString(number) {
подумай, можно ли обойтись без этой функции?

2016-10-27 13:05 UTC, mironov-alexey commented on robbery.js
> +    if (number === 0) {
кажется, это условие дублирует условие ниже)

2016-10-27 13:05 UTC, mironov-alexey commented on robbery.js
> +function createDateFromMinures(minutes) {
то же самое

2016-10-27 13:05 UTC, mironov-alexey commented on robbery.js
> +        day: WEEKDAY[day],
`WEEK_DAYS`?

2016-10-27 13:05 UTC, mironov-alexey commented on robbery.js
> +        hours: convertToString(hours),
зачем дописывать нолики-то?

2016-10-27 13:05 UTC, mironov-alexey commented on robbery.js
> +    var day = Math.floor(minutes / DAY);
`WEEK_DAYS` кстати можно использовать здесь, а не в самом объекте, который возвращает эта функция

2016-10-27 13:05 UTC, mironov-alexey commented
🍅

2016-10-30 16:22 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 16:30 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 18:00 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 18:14 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 18:16 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-10-30 18:19 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-10-30 18:47 UTC, m1ralx requested changes

2016-10-30 18:47 UTC, mironov-alexey commented on robbery.js
> +    var start = getMinutes(timeFrom); // in minuts
комментарий можно убрать, он абсолютно бесполезен

2016-10-30 18:47 UTC, mironov-alexey commented on robbery.js
> +function getMinutes(str) {
входной параметр можно назвать более осмысленно

2016-10-30 18:47 UTC, mironov-alexey commented on robbery.js
> +    return (parseInt(partsTime[1], 10) * HOUR + parseInt(partsTime[2], 10));
внешние скобки не нужны

2016-10-30 18:47 UTC, mironov-alexey commented on robbery.js
> +
отступ не нужен

2016-10-30 18:47 UTC, mironov-alexey commented on robbery.js
> +    return (parseInt(time.match(TIME)[3], 10));
регэксп лучше назвать `TIME_FORMAT`

2016-10-30 18:47 UTC, mironov-alexey commented on robbery.js
> +
отступ

2016-10-30 18:47 UTC, mironov-alexey commented on robbery.js
> +
и тут

2016-10-30 18:47 UTC, mironov-alexey commented on robbery.js
> +function isIntersects(bTime, start, end) {
что такое `bTime`? Назови понятнее

2016-10-30 18:47 UTC, mironov-alexey commented on robbery.js
> +function isIntersects(bTime, start, end) {
ну и тут два интервала пересекаются, так что видимо `is` не очень хорошо

2016-10-30 18:48 UTC, mironov-alexey commented
🍅

2016-11-01 14:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-01 14:40 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-11-01 20:14 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-11-02 12:22 UTC, mironov-alexey commented on robbery.js
> +        var dataTimeStart = times[i].from.match(DATE);
тут префикс `data` какой смысл несёт?

2016-11-02 12:24 UTC, mironov-alexey commented on robbery.js
> +    return (WEEKDAY.indexOf(time[1]) * DAY +
видимо страшное форматирование может намекать на две вещи, которые можно сделать:
Как минимум -- отформатировать так, чтобы выровнялось по левому краю
В идеале -- создать переменные с осмысленными названиями и возвращать нужную комбинацию из этих переменных

2016-11-02 12:24 UTC, m1ralx commented on robbery.js
> +
тут линтер правда требует пустую строку?

2016-11-02 12:25 UTC, mironov-alexey commented on robbery.js
> +    if (busyTimes.every(function (busyTime) {
и я всё-таки советую выносить длинные условия (тем более такие, которые требуют вызова функции `every`/`some`) в отдельные, осмысленно названные перменные

2016-11-02 12:25 UTC, mironov-alexey commented on robbery.js
> +
тут можно не вставлять пустые строки

2016-11-02 12:26 UTC, mironov-alexey commented on robbery.js
> +
и тут

2016-11-02 12:26 UTC, mironov-alexey commented on robbery.js
> +    return [start, end];
лучше всё-таки работать с интервалами, которые хранятся в виде объекта с полями `from` и `to` так будет понятнее, чем `[0]` и `[1]`

2016-11-02 12:27 UTC, m1ralx commented on robbery.js
> +function getInterval(timeFrom, timeTo) {
`getIntervalInMinutes` хотя бы, а то не очень понятно, что делает эта функция, если не прочитать её код

2016-11-02 12:28 UTC, mironov-alexey commented on robbery.js
> +        return '0' + String(number);
можно без `String(..)`

2016-11-02 12:30 UTC, mironov-alexey commented on robbery.js
> +    var minutess = minutes % DAY % HOUR;
`minutess`? Кажется, если приходится так упарываться с названиями переменных, то с кодом что-то не так. Нужно подумать и сделать аккуратно

2016-11-02 12:30 UTC, mironov-alexey commented
🍅

2016-11-02 14:07 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2016-11-02 14:12 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-11-02 14:28 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-11-02 15:28 UTC, mironov-alexey commented on robbery.js
> +var TIME_FORMAT = /^(\d\d):(\d\d)[+](\d)$/;
`\d\d` можно записывать как `\d{2}`
`[+]` можно записывать как `\+`
`[ ]` можно записывать как `\s`
Чем отличается запись `[:]` от записи `:`?

2016-11-02 15:29 UTC, mironov-alexey commented on robbery.js
> +function getShiftInHours(time) {
Вместо `ShiftInHours` лучше использовать `Timezone`

2016-11-02 15:30 UTC, mironov-alexey commented
🚀

2016-11-02 18:45 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-11-02 19:25 UTC, gogoleff commented
🚀

2016-11-02 19:30 UTC, gogoleff commented
🚀

2016-11-02 20:00 UTC, gogoleff commented
🚀

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +var DATE = /^([А-Я]{2})?[ ]?(\d{2})[:](\d{2})\+(\d+)$/;
`А-Я` избыточно, у тебя ограниченный набор сущностей

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +var DATE = /^([А-Я]{2})?[ ]?(\d{2})[:](\d{2})\+(\d+)$/;
Для пробела есть специальный более семантичный символ, нежели`[ ]?`

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +var DATE = /^([А-Я]{2})?[ ]?(\d{2})[:](\d{2})\+(\d+)$/;
Зачем один символ оборачивать в группу – `[:]` ?

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +var DATE = /^([А-Я]{2})?[ ]?(\d{2})[:](\d{2})\+(\d+)$/;
В конце выражения `(\d+)` явно избыточно, для временной зоны можно указать ограниченное кол-во цифр

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +var TIME_FORMAT = /^(\d\d):(\d\d)[+](\d)$/;
Продублирую комментарий студентора:

* \d\d можно записывать как \d{2}
* [+] можно записывать как \+

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +var HOUR = 60;
«Час равен шестидесяти»? –  стоит назвать переменную более осмысленно

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +var DAY = 24 * HOUR;
Стоит назвать переменную более осмысленно

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +    var dayInMinutes = WEEKDAY.indexOf(time[1]) * DAY;
Здесь уже теряется контекст – что скрывается за первым индексом.
Предлагаю завести функцию **parseDate**, которая бы возвращала уже готовый для работы объект.

Например:

```js
return {
  day: 'ПН'
  hour: 20,
  minit: 15,
  timezone: 5
}
```

Преобразования типов можно сразу сделать в этой функции, так мы замкнём похожую логику в одном месте!

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +var TIME_FORMAT = /^(\d\d):(\d\d)[+](\d)$/;
Не уверен, что необходимы две регулярки. Смотри комментарий про parseDate

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +    return (parseInt(time.match(TIME_FORMAT)[3], 10));
Зачем оборачивать в скобки?

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +    var start = getMinutes(timeFrom);
В переменных `start` и `end` нет необходимости

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +    var times = concatTimeline(schedule);
Я бы вернул код функции в этот метод, тогда результа можно зачейнить:

```js
return Object
  .keys(schedule)
  .reduce()
  .map()

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +    return String(number);
Есть более изящный способ:

```js
('0' + number).slice(-2)

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +            return template.replace(/%HH/, date.hours)
Зачем регулярное выражение?

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +        if (period !== undefined) {
Бессмысленная конструкция, можно просто `return period`

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +        if (period !== undefined) {
И получается переменная не нужна

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +        if (startRobbery !== undefined) {
Просто ` if (startRobbery) {`

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +    var timeline = getTimeline(schedule, timeZone);
timeline -> busyTimes (как везде, стоит быть последовательным в именованиях)

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +    for (var i = 0; i < 3; i++) {
i -> day (как везде, стоит быть последовательным в именованиях)

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +function searchTimeRobbery(timeBank, time, busyTime, day) {
time -> duration (как везде, стоит быть последовательным в именованиях)

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +    return !(busyTime.end <= start || busyTime.start >= end);
Лучше не использовать отрицания по возможности – одна лишняя логическая операция

2016-11-04 14:38 UTC, gogoleff commented on robbery.js
> +function searchTimeRobbery(timeBank, time, busyTime, day) {
Теоретически `timeBank` можно преобразовать как часть `busyTime`. Банк, как ещё один грабитель, который должен быть свободен ;)

2016-11-04 14:39 UTC, gogoleff commented
:tom

2016-11-04 14:39 UTC, gogoleff commented
🍅

2016-11-06 20:26 UTC, IrinaShmonina commented on robbery.js
> +        if (period !== undefined) {
Это в цикле, если сразу вернуть period, то может не найтись следующий, хотя он есть.

2016-11-06 20:35 UTC, IrinaShmonina commented on robbery.js
> +        if (startRobbery !== undefined) {
Если там будет 0, то будет false, хотя 0 это допустимое начало ограбления.

2016-11-08 08:19 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 16 из 16

2016-11-08 18:56 UTC, gogoleff commented on robbery.js
> +var TIME_REGEX = /(?:([ПН|ВТ|СР|ЧТ|ПТ|СБ|ВС]{2})\s)?(\d{2}):(\d{2})\+(\d{1,2})/;
`([ПН|ВТ|СР|ЧТ|ПТ|СБ|ВС]{2})` -> `(ПН|ВТ|СР|ЧТ|ПТ|СБ|ВС)`

2016-11-08 18:56 UTC, gogoleff commented on robbery.js
> +    var partsTime = hoursAndMinutes.match(TIME_REGEX);
Почему не использовать здесь `parseDate()`

2016-11-08 18:57 UTC, gogoleff commented
@IrinaShmonina В целом не критичные пожелания остались, задача принята

2016-11-08 18:57 UTC, closed without merging