Савенков Илья
urfu-2016/javascript-task-3 pull request #65
Opened 2016-10-27 02:33 UTC by slaeme

2016-10-27 04:39 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-27 04:39 UTC, honest-hrundel commented
@VasiliiKuznecov обрати внимание решено доп. задание

2016-10-27 17:09 UTC, VasiliiKuznecov commented on robbery.js
> +    var self = this;
Почему не использовать просто `this`?

2016-10-27 17:11 UTC, VasiliiKuznecov commented on robbery.js
> +    robberySchedule.fillTimeTable(schedule, workingHours);
Лучше отделять объявление переменных пустой строкой

2016-10-27 17:15 UTC, VasiliiKuznecov commented on robbery.js
> +    robberySchedule.fillTimeTable(schedule, workingHours);
Наверное, можно вызывать `fillTimeTable` в конструкторе `robberySchedule`

2016-10-27 17:20 UTC, VasiliiKuznecov commented on robbery.js
> +function Time(weekdays) {
Странный объект: не хранит в себе никаких данных про конкретное время. Кажется, что это просто набор функций. Тогда нужен ли этот объект или можно просто описать эти функции, без объекта?

2016-10-27 17:22 UTC, VasiliiKuznecov commented on robbery.js
> +        var min = self.getMinutes(time);
Не стоит сокращать названия переменных. А то мы к минимуму прибавляем какие-то минуты.

2016-10-27 17:29 UTC, VasiliiKuznecov commented on robbery.js
> +            if ({}.hasOwnProperty.call(schedule, thief)) {
`schedule.hasOwnProperty(thief)`

2016-10-27 17:29 UTC, VasiliiKuznecov commented on robbery.js
> +            var differentTZ = houseTimeZone - from.zone;
не сокращай

2016-10-27 17:30 UTC, VasiliiKuznecov commented on robbery.js
> +        var houseTimeZone = self.timeObj.convertStrToTime('ПН ' + workingHours.from).zone;
почему `house`? Вроде как банк они грабят)

2016-10-27 17:32 UTC, VasiliiKuznecov commented on robbery.js
> +    self.suitableWithFilter = robberySchedule.filter(30);
что за 30?

2016-10-27 17:33 UTC, VasiliiKuznecov commented on robbery.js
> +        return day.toString() + ' ' + hourStr + ':' + minutesStr;
Зачем хранить в памяти время в виде строки? Из-за этого нам каждый раз придется парсить строку заново и снова собирать, когда можно было распарсить один раз и всегда работать с уже готовыми данными.
Срочно переписывай, пока никто не заметил!

2016-10-27 17:35 UTC, VasiliiKuznecov commented on robbery.js
> +    self.shiftTimeZone = function (time, different) {
Что есть `different`? Непонятное название

2016-10-27 17:35 UTC, VasiliiKuznecov commented on robbery.js
> +            zone: Number(parseTime[3])
`timezone`?

2016-10-27 17:38 UTC, VasiliiKuznecov commented on robbery.js
> +        if (parseTime.length === 5) {
Почему может быть не 5 и почему если не 5, то что-то делаем после этого?

2016-10-27 17:41 UTC, VasiliiKuznecov commented on robbery.js
> +        var parseTime = timeStr.match(/^(.{2}) (\d{2}):(\d{2})\+(\d)+$/);
Возможно, лучше будет парсить split'ами - более читаемо

2016-10-27 17:42 UTC, VasiliiKuznecov commented on robbery.js
> +        var minutes = (time.minutes < 10) ? '0' + time.minutes.toString() : time.minutes.toString();
повторение кода для `hours` и `minutes`

2016-10-27 17:44 UTC, VasiliiKuznecov commented on robbery.js
> +            template = template.replace('%DD', day);
тут можно использовать цепочку вызовов (чейнинг):

``` javascript
var formattedTime = template
    .replace('%HH', parseTime[2]);
    .replace('%MM', parseTime[3]);
    .replace('%DD', day);
```

2016-10-27 17:46 UTC, VasiliiKuznecov commented on robbery.js
> +    self.addNode = function (key, who, status) {
Что такое `status`?

2016-10-27 17:50 UTC, VasiliiKuznecov commented on robbery.js
> +    self.addBusy = function (works, thief, houseTimeZone) {
Кажется, в названии есть какая-то недосказанность. Добавить занятые что?
И что такое `works`, `thief` - тоже непонятно, слишком общие названия

2016-10-27 17:53 UTC, VasiliiKuznecov commented on robbery.js
> +    self.getTimeTable = function () {
Кажется, этот метод нигде не используется

2016-10-27 17:56 UTC, VasiliiKuznecov commented on robbery.js
> +    self.addNextMoment = function (filterSuitable, lastTime, i, stepInMinutes) {
что такое i, непонятно

2016-10-27 18:10 UTC, VasiliiKuznecov commented on robbery.js
> +        var sortedKeys = Object.keys(self.timeTable).sort();
Понял, зачем ты делаешь из времени строку. Но лучше так не делать: выглядит как хак, легко ошибиться при сравнении строк и ты преобразуешь лишний раз из строки в объект и обратно.
Вместо этого, можно  скидать объекты с распаршенным временем в массив (вместо объекта `timeTable`), а потом отсортировать его, используя свою функцию сортировки объектов с временем. Получится то же самое, что сортировка ключей, но без хаков и лишних преобразований

2016-10-27 18:11 UTC, VasiliiKuznecov commented
🍅 Жду, пока сделаешь сортировку не по строкам, а по распаршенным объектам. Потом еще раз глянем =)

2016-10-28 03:21 UTC, slaeme commented on robbery.js
> +        var sortedKeys = Object.keys(self.timeTable).sort();
Поиск в массиве объектов, даже отсортированном -  медленная операция, поэтому хочется использовать хеш (ассоциативные массивы с ключами). Очень жаль, что в js ключом может быть только строка или число, поэтому это выглядит как хак. Побороть постоянное преобразование можно, если хранить объект со временем в записи хеш-таблицы. Можно будет так реализовать?

2016-10-28 03:48 UTC, VasiliiKuznecov commented on robbery.js
> +        var sortedKeys = Object.keys(self.timeTable).sort();
Так ты и так сортируешь массив ключей

2016-10-28 03:49 UTC, VasiliiKuznecov commented on robbery.js
> +        var sortedKeys = Object.keys(self.timeTable).sort();
У тебя массив ключей такой же по размеру как был бы массив объектов, так что тут выигрыша никакого нет

2016-10-28 03:51 UTC, VasiliiKuznecov commented on robbery.js
> +        var sortedKeys = Object.keys(self.timeTable).sort();
А разве ты где-то используешь поиск?

2016-10-28 05:38 UTC, slaeme commented on robbery.js
> +        var sortedKeys = Object.keys(self.timeTable).sort();
Да, когда заношу записи в "таблицу":

``` javascript
self.addNode = function (key, who, status) {
        var node = self.timeTable[key];
        if (node !== undefined) {
            node[who] = status;
        } else {
            self.timeTable[key] = {};
            self.timeTable[key][who] = status;
        }
    };
```

Если использовать массив, то для каждой записи мне придется искать в массиве объектов.

2016-10-30 17:12 UTC, honest-hrundel commented
:tomato: Пройдено тестов 11 из 19

2016-10-30 20:10 UTC, honest-hrundel commented
:tomato: Пройдено тестов 10 из 19

2016-10-30 20:57 UTC, honest-hrundel commented
:tomato: Пройдено тестов 18 из 19

2016-10-30 23:51 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-10-30 23:51 UTC, honest-hrundel commented
@VasiliiKuznecov обрати внимание решено доп. задание

2016-11-01 17:44 UTC, VasiliiKuznecov commented on robbery.js
> +        var splitTime = timeStr.split(/[ :+]+/);
Зачем + в регулярке?

2016-11-01 17:44 UTC, VasiliiKuznecov commented on robbery.js
> +    self.tableMoments = [];
`momentsTable` звучало бы лучше

2016-11-01 17:45 UTC, VasiliiKuznecov commented on robbery.js
> +    var self = this;
Так и не ответил, почему не используешь просто `this`

2016-11-01 17:47 UTC, VasiliiKuznecov commented on robbery.js
> +            time: new Date(2015, 5, time.day, time.hour + shiftTimezone, time.minutes, 0, 0),
Почему именно 2015, 5?)

2016-11-01 17:49 UTC, VasiliiKuznecov commented on robbery.js
> +                who: who,
Лучше наверное назвать не в форме вопроса, а именно существительным

2016-11-01 17:52 UTC, VasiliiKuznecov commented on robbery.js
> +    function addTimeBankInTimeTable() {
`addBankNodes` - короче и вроде как понятнее, что мы именно ноды добавляем

2016-11-01 17:53 UTC, VasiliiKuznecov commented on robbery.js
> +    function addTimeThiefInTable(bankTimezone) {
`addThiefsNodes`
И еще, я бы использовал существительное robbers, раз у нас есть еще в коде слово robbery. Чтобы не казалось, что это про разные вещи

2016-11-01 17:55 UTC, VasiliiKuznecov commented on robbery.js
> +            }
После if сделал бы пустую строку, так как if и то что ниже - это разная логика вообще

2016-11-01 17:57 UTC, VasiliiKuznecov commented on robbery.js
> +            var toDoList = schedule[thief];
`toDoList` странное название) Так же не написано, что ему надо сделать) Просто расписание, когда занят
Может, `thiefShedule`?

2016-11-01 17:59 UTC, VasiliiKuznecov commented on robbery.js
> +                var toTime = parseTime(timeWhenBusy.to);
Перенес бы все объявления переменных в начало цикла и сделал после них пустую строку

2016-11-01 18:01 UTC, VasiliiKuznecov commented on robbery.js
> +    self.tableMoments = [];
И, может, table вообще не нужен? Вроде нового смысла не несет, а то что это массив понятно из того, что множественное чилсо

2016-11-01 18:03 UTC, VasiliiKuznecov commented on robbery.js
> +    self.tableMoments = [];
И не moments, а events. И вместо `getNode` - `getEvent`, потому что там же эти события хранятся по сути

2016-11-01 18:06 UTC, VasiliiKuznecov commented on robbery.js
> +    function addTimeBankInTimeTable() {
Странный у тебя объект, вроде это метод класса, но оформлен просто как функция, а не метод

2016-11-01 18:06 UTC, VasiliiKuznecov commented on robbery.js
> +    function addTimeThiefInTable(bankTimezone) {
тоже по идее метод

2016-11-01 18:07 UTC, VasiliiKuznecov commented on robbery.js
> +    function fillTimeTable() {
И это метод

2016-11-01 18:08 UTC, VasiliiKuznecov commented on robbery.js
> +    var self = this;
а вот тут зачем `this` и `self` неясно, это же функция должна быть, в ней этого не должно использоваться

2016-11-01 18:08 UTC, VasiliiKuznecov commented on robbery.js
> +    self.robberySchedule = new RobberySchedule(schedule, duration, workingHours);
Почему не просто в переменную сложить?

2016-11-01 18:10 UTC, VasiliiKuznecov commented on robbery.js
> +    function parseTime(timeStr) {
А просто функции лучше не объявлять посреди конструктора объекта, а либо все в начале файла, либо все в конце. (Лучше наверное в конце)

2016-11-01 18:11 UTC, VasiliiKuznecov commented on robbery.js
> +            var toTime = parseTime(day + ' ' + workingHours.to);
То же самое про объявления переменных в начале и с отступом

2016-11-01 18:15 UTC, VasiliiKuznecov commented on robbery.js
> +        self.thieves.forEach(function (thief) {
Можно сделать намного красивее, используя `every`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

2016-11-01 18:19 UTC, VasiliiKuznecov commented on robbery.js
> +                self.tableMoments.push(getNode(toTime, thief, true, shiftTimezone));
Можно сделать метод `addNode` и запихнуть `self.tableMoments.push` туда

2016-11-01 18:21 UTC, VasiliiKuznecov commented on robbery.js
> +    function getBeginCurrentMoment() {
зачем слово `current`?

2016-11-01 18:22 UTC, VasiliiKuznecov commented on robbery.js
> +            currentMoment.duration = (nextNode.time - node.time) / (1000 * 60);
пустая строка после объявления переменных

2016-11-01 18:26 UTC, VasiliiKuznecov commented on robbery.js
> +            currentMoment.duration = (nextNode.time - node.time) / (1000 * 60);
1000 \* 60 в константу

2016-11-01 18:30 UTC, VasiliiKuznecov commented on robbery.js
> +            function convertNumberToString(number) {
функцию в конец файла

2016-11-01 18:32 UTC, VasiliiKuznecov commented on robbery.js
> +            function convertNumberToString(number) {
и название лучше сделать другое, как-то отображающее, что 0 добавляется в начало (что это форматирование минут/часов)

2016-11-01 18:36 UTC, VasiliiKuznecov commented on robbery.js
> +            if (self.currentIndex >= self.allSuitableMoments.length) {
Что будет, если подходящее время не существует и мы вызываем `format`?

2016-11-01 18:36 UTC, VasiliiKuznecov commented on robbery.js
> +            var halfHour = 30;
в константу

2016-11-01 18:39 UTC, VasiliiKuznecov commented
:tomato: Посмотрел, намного лучше стало) Но надо с классом разобраться (либо убрать его)) )

2016-11-01 19:51 UTC, slaeme commented on robbery.js
> +            var toDoList = schedule[thief];
thiefSсhedule тогда уж

2016-11-01 20:01 UTC, slaeme commented on robbery.js
> +            time: new Date(2015, 5, time.day, time.hour + shiftTimezone, time.minutes, 0, 0),
там 1ое число - это ПН, 2ое - вторник и так далее, очень удобно.

2016-11-01 20:31 UTC, slaeme commented on robbery.js
> +            if (self.currentIndex >= self.allSuitableMoments.length) {
```javascript
self.currentIndex // 0
self.allSuitableMoments.length //0
self.currentIndex >= self.allSuitableMoments.length //true 
```
функция вернет пустую строку

2016-11-01 20:34 UTC, slaeme commented on robbery.js
> +    var self = this;
боюсь, что он будет означать что-то другое

2016-11-01 21:03 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-11-01 21:04 UTC, honest-hrundel commented
@VasiliiKuznecov обрати внимание решено доп. задание

2016-11-03 18:45 UTC, VasiliiKuznecov commented on robbery.js
> +    this.addEvent = function (timeStr, who, available, shiftTimezone) {
и аргумент тоже бы `name` назвал

2016-11-03 18:45 UTC, VasiliiKuznecov commented on robbery.js
> +    this.addEvent = function (timeStr, who, available, shiftTimezone) {
не сокращай, `timeString`

2016-11-03 18:46 UTC, VasiliiKuznecov commented on robbery.js
> +        var self = this;
кажется, не нужно

2016-11-03 18:49 UTC, VasiliiKuznecov commented on robbery.js
> +        for (var thief in schedule) {
неочевидно, откуда берется `schedule`, лучше прокидывать в аргументах либо записать в `this`

2016-11-03 18:51 UTC, VasiliiKuznecov commented on robbery.js
> +    function getBeginMoment(robbers) {
Это тоже лучше сделать методом класса и `robbers` не прокидывать, а обращаться через `this`

2016-11-03 18:52 UTC, VasiliiKuznecov commented on robbery.js
> +    function isSuitableMoment(event, robbers) {
Тоже метод

2016-11-03 18:53 UTC, VasiliiKuznecov commented on robbery.js
> +    function parseTime(timeStr, weekdays) {
А эту функцию можно прям в конец файла, а не в объекте - объект может и не знать как парсить время
и `timeString`

2016-11-03 18:56 UTC, VasiliiKuznecov commented
Вроде небольшие замечания, остальное ок, так что 🚀

2016-11-07 19:46 UTC, maxvipon commented on robbery.js
> +        var sortedKeys = Object.keys(self.timeTable).sort();
> Очень жаль, что в js ключом может быть только строка или число

В струтктуре [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) ключем может быть любая js-сущность.

2016-11-08 20:21 UTC, maxvipon requested changes

2016-11-08 20:21 UTC, maxvipon commented on robbery.js
> +            self.addEvent(day + ' ' + workingHours.from, 'bank', true);
чтобы не избавиться от `self` почитай спецификацию функции `forEach`.

2016-11-08 20:21 UTC, maxvipon commented on robbery.js
> +    var robberySchedule = new RobberySchedule(schedule, duration, workingHours);
Расскажи, пожалуйста, почему ты выбрал использование конструктора?

2016-11-08 20:22 UTC, maxvipon commented
Прошу прощения, я вчера написал комментов, а кнопку "Submit review" не нажал – давненько не заходил на гихаб, как-то упустил сие новшество.

2016-11-08 21:51 UTC, honest-hrundel commented
:green_apple: Пройдено тестов 19 из 19

2016-11-08 21:51 UTC, honest-hrundel commented
@maxvipon обрати внимание решено доп. задание

2016-11-08 21:51 UTC, slaeme commented on robbery.js
> +    var robberySchedule = new RobberySchedule(schedule, duration, workingHours);
Согласен, тут он не нужен, оставил только функцию.

2016-11-08 21:53 UTC, slaeme commented on robbery.js
> +            self.addEvent(day + ' ' + workingHours.from, 'bank', true);
Когда убрал "класс" потребности в this не стало, но в спецификации нашел, что 
```javascript
 this.weekdays.forEach(function (day) {
            this.addEvent(day + ' ' + workingHours.from, 'bank', true);
}, this); 
```
должно работать

2016-11-09 07:49 UTC, maxvipon commented on robbery.js
> +            self.addEvent(day + ' ' + workingHours.from, 'bank', true);
👌

2016-11-09 07:52 UTC, maxvipon approved these changes

2016-11-09 07:52 UTC, closed without merging